1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [1]:
import numpy as np
import math
import timeit

m = np.arange(12).reshape((3,4))
print("Media di m: ", m.mean())
print("Media delle colonne di m: ", m.mean(0))
print("Media delle righe di m: ", m.mean(1))

Media di m:  5.5
Media delle colonne di m:  [4. 5. 6. 7.]
Media delle righe di m:  [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [2]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("Outer product with np.outer:\n", np.outer(u,v))
for_outer = np.zeros((len(u), len(v)))
for i in range(len(u)):
    for j in range(len(v)):
        for_outer[i, j]=u[i]*v[j]
print("Outer product with for:\n", for_outer)
tiled_u = np.tile(u, (len(u), 1))
tiled_v = np.tile(v, (len(v), 1))
tiled_outer = tiled_v*tiled_u.T
print("Outer product with numpy.tile:\n", tiled_outer)

Outer product with np.outer:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Outer product with for:
 [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
Outer product with numpy.tile:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [3]:
a = 3*np.random.rand(10, 6)
mask = (a>0.3)
print(a[mask])

[1.37056194 0.62488324 2.53857367 2.21826088 0.44427059 2.48016256
 1.33740806 2.2929698  1.13612156 2.35499482 1.86751202 0.64591974
 1.08228919 1.11112753 0.98666064 2.75351434 1.81535537 2.82740008
 1.00591906 1.65753996 1.34601901 2.55139421 1.22380229 1.72545989
 1.05759719 2.91350417 0.57550704 2.32315814 2.81049082 2.78262568
 2.89438748 1.98236767 1.1511501  1.13617205 2.46466439 0.82045069
 1.60636574 1.55519955 1.1013839  1.73198948 2.90673458 1.41684872
 1.57207214 1.0772648  1.43819687 1.48651488 0.82320915 2.01563844
 1.36854763 0.52748124 1.47194104 2.97079041 1.8946733  1.98287556]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [4]:
a = np.linspace(0, 2*math.pi, 100)
print(a,"\n")
print(a[::10],"\n")
print(a[::-1], "\n")
mask = (np.sin(a) - np.cos(a)<0.1)
print(a[mask])

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [5]:
table = np.zeros((10, 10), "int")
for i in range(1, 11):
    table[i-1] = np.arange(i, 11*i, i)
print(table, "\n")
print("Trace of that matrix: ", np.trace(table), "\n")
diag2=[]
for c in range(table.shape[1]-1):
    diag2.append(table[c,c+1])
print(diag2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] 

Trace of that matrix:  385 

[2, 6, 12, 20, 30, 42, 56, 72, 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [6]:
cities = ["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]
distances = [0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]
grid = np.zeros((len(cities), len(cities)))
for i in range(len(cities)):
    for j in range(i + 1, len(cities)):
        grid[i][j] = distances[j]-distances[i]
        grid[j][i] = grid[i][j]
KMgrid=grid*0.6213712
print(grid)

[[   0.  198.  303.  736.  871. 1175. 1475. 1544. 1913. 2448.]
 [ 198.    0.  105.  538.  673.  977. 1277. 1346. 1715. 2250.]
 [ 303.  105.    0.  433.  568.  872. 1172. 1241. 1610. 2145.]
 [ 736.  538.  433.    0.  135.  439.  739.  808. 1177. 1712.]
 [ 871.  673.  568.  135.    0.  304.  604.  673. 1042. 1577.]
 [1175.  977.  872.  439.  304.    0.  300.  369.  738. 1273.]
 [1475. 1277. 1172.  739.  604.  300.    0.   69.  438.  973.]
 [1544. 1346. 1241.  808.  673.  369.   69.    0.  369.  904.]
 [1913. 1715. 1610. 1177. 1042.  738.  438.  369.    0.  535.]
 [2448. 2250. 2145. 1712. 1577. 1273.  973.  904.  535.    0.]]


7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [7]:
def measure_time(func):
    def wrapper(*args, **kwargs):
        Tstart = timeit.default_timer()
        result = func(*args, **kwargs)
        Tend = timeit.default_timer()
        Texec = Tend - Tstart
        print("This function took {:.6f} seconds to run.".format(Texec))
        return result
    return wrapper

@measure_time
def prime_n(array):
    primes = []
    for x in array:
        if x==1 or x==0:
            is_prime=False
        else:
            is_prime=True
        for i in range(2, int(x/2)+1):
            if x % i == 0:
                is_prime = False
        if is_prime:
            primes.append(x)
    return primes

@measure_time
def sieve_prime(array):
    max_num = max(array)
    sieve = np.ones(max_num + 1, dtype=bool)
    sieve[:2] = False
    for n in range(2, int(np.sqrt(max_num)) + 1):
        if sieve[n]:
            sieve[n * n::n] = False
    return array[sieve]
    
N=2000
numbers = np.arange(N)
print("Prime numbers:\n", prime_n(numbers))
print("Prime numbers using sieve of eratosthenes:\n", sieve_prime(numbers))

'''
The time of execution of the function prime_n grows with proportion to N^2 (with N=100 the time is 0.000641, with N=1000 is 0.057 and with N=2000 is 0.237), while sieve_prime's execution time is almost linear in the dimension of N (with N=100 the time is 0.000076, with N=1000 is 0.000108 and with N=2000 is 0.000199).
'''


This function took 0.153060 seconds to run.
Prime numbers:
 [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 11

"\nThe time of execution of the function prime_n grows with proportion to N^2 (with N=100 the time is 0.000641, with N=1000 is 0.057 and with N=2000 is 0.237), while sieve_prime's execution time is almost linear in the dimension of N (with N=100 the time is 0.000076, with N=1000 is 0.000108 and with N=2000 is 0.000199).\n"

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [8]:
walkers, times = 1000, 200
steps = np.random.randint(2, size=(walkers, times))*2-1
progress = np.zeros(steps.shape, "int")
for i in range(walkers):
    for j in range(times):
        progress[i, j]=progress[i, j-1]+steps[i, j]
print("Total walked distance of each walker:\n", progress[:, times-1])
square_prog = progress * progress
mean_step=np.zeros(times)
for c in range(times):
    mean_step[c]=sum(square_prog[:, c])/walkers
print("Mean of squared distances at each time's step:\n", mean_step)

Total walked distance of each walker:
 [ 10   0  -8   2 -22  16  10  24   2  18  14   4   0  -6  26  16  14   8
 -10  12  10 -24  22  18 -10 -12  22   6 -14  20 -30 -14   2   2  -2  26
  20  -4  16  14   2  28 -16   0   4 -10  -2  16  10 -36  14 -22   2  12
 -16  12 -14  18   4 -18  10   2  12  -6 -14  -2   2  22   4  16  18 -10
  -8   8  -8 -16 -28   2  -8   0  12   8   6  -4   0  10   8   6 -10   0
 -26 -12  -8 -12   4   0 -12  -2  -2  -8   4   8   8  20  -2   4  -8 -10
 -16  26  -8  22 -10 -10  20   4   4   8 -26   0  22 -22 -14  -2 -24  12
  -8 -22   0   2  -6  -2  -2  -6  -2  18   6   2 -24  18  16  16 -18 -18
 -28   2  14  -6  14  10  16   2  16  20 -22 -24   2   0  -4   8  14   2
 -26  -4   0  -6  28  18   6 -20   6   6 -10 -20 -26  16  -4   4   0 -18
   8 -10   4 -14  12   6   2  36   2  -6   2   4   8   2  -2 -14  -6  -4
   8   0  -8 -16  -4 -18  16 -20   2 -14   6 -16  -4  -8   6   8   2  -8
  -8  10   4 -32   8  20  -6  -2  -4  14 -28 -16  -6  -4  22  26   0  -6
 -20   4  -2