1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [124]:
import numpy as np
import timeit
import numpy.random as npr

In [ ]:
m = np.arange(12).reshape((3,4))
print(m)

print('Total mean',m.mean())
print('Mean for each col',m.mean(axis=0))
print('Mean for each row',m.mean(axis=1))


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [ ]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print('u =',u)
print('v =',v)

print('\nusing the function outer in numpy\n',np.outer(u,v))
print('\nusing a nested for loop or a list comprehension')
matrix = []
for i in range(len(u)):
    for j in range(len(v)):
        matrix.append(u[i]*v[j])
    
    
A = np.array(matrix).reshape(len(u),len(v))
print(A)

u = u[:,np.newaxis]
print('\nusing numpy broadcasting operations\n',u*v)


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [ ]:
import numpy.random as npr
A = npr.uniform(low=0.0, high=3.0, size=(10,6))
print('10 x 6 matrix with rand values between 0 and 3\n',A)
mask =(A<0.3)
A[A<0.3]=0
print('\n10 x 6 matrix modified\n',A)

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [ ]:
pi = np.linspace(0,2*np.pi,100)
print('array pi:\n',pi)
print('Extract every 10th element using the slice notation:\n',pi[::10])
print('Reverse the array using the slice notation:\n',pi[::-1])
print('Extract elements where the absolute difference between the sin and cos functions evaluated for that element is  <0.1')
print(pi[np.sin(pi)-np.cos(pi)<0.1])



5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [ ]:
mx = np.fromfunction(lambda i,j: (i+1)*(j+1), (10,10))
print('Matrix:\n',mx)

print('Find the trace of the matrix: ',np.sum(np.diag(mx)))
print('Extract the anti-diagonal matrix (this should be array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])):')
print(np.diag(np.fliplr(mx)))
print('Extract the diagonal offset by 1 upwards (this should be array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])):')
print(np.diag(mx,1))

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [ ]:
dist = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
print(dist)
dist_vertical = dist.reshape(10,1)
print(dist_vertical)
matrix = np.triu(dist-dist_vertical)
print(matrix)
matrix_km = matrix * 1.60934
print(matrix_km)

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [122]:
def primeNumbers(N):
    arr = np.arange(2,N)
    mask = (arr %2!=0)
    mask[0]=True
    arr = arr[mask]
    mask = mask[mask]
    for j in arr[arr>2]:
        for i in arr[arr<j]:
            if (j % i) == 0:
                arr = arr[arr != j]
                break
    return arr
    
def primeNumbersEratosthenes(N):
    arr = np.arange(2,N)
    mask = (arr % 2 != 0)
    arr = arr[mask]
    mask = mask[mask]
    primes = np.array([2])
    while arr.shape[0]:
        p = arr[0]
        arr = arr[arr % p != 0]
        
        primes =  np.append(primes, p)

    return primes

    
    
    
print(primeNumbers(100))
print(primeNumbersEratosthenes(100))

importing = "import numpy as np"
primeNumbersForMeasurments = '''
def primeNumbers(N):
    arr = np.arange(2,N)
    mask = (arr %2!=0)
    mask[0]=True
    arr = arr[mask]
    mask = mask[mask]
    for j in arr[arr>2]:
        for i in arr[arr<j]:
            if (j % i) == 0:
                arr = arr[arr != j]
                break
    return arr

primeNumbers(100)
'''

primeNumbersEratosthenesForMeasurments = '''
def primeNumbersEratosthenes(N):
    arr = np.arange(2,N)
    mask = (arr % 2 != 0)
    arr = arr[mask]
    mask = mask[mask]
    primes = np.array([2])
    while arr.shape[0]:
        p = arr[0]
        arr = arr[arr % p != 0]
        
        primes =  np.append(primes, p)

    return primes
primeNumbersEratosthenes(100)
'''

print("Execution time", timeit.timeit(stmt=primeNumbersForMeasurments, setup = importing, number=1000))
print("Execution time", timeit.timeit(stmt=primeNumbersEratosthenesForMeasurments, setup = importing, number=1000))

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
Execution time 0.11178229202050716
Execution time 0.08797012499417178


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [127]:
matrix = npr.randint(0, 2, (1000,200)) * 2 - 1


[[ 1 -1 -1 ... -1 -1  1]
 [-1 -1  1 ... -1 -1  1]
 [-1  1 -1 ...  1 -1  1]
 ...
 [ 1  1 -1 ...  1 -1  1]
 [-1 -1  1 ... -1  1  1]
 [-1  1  1 ...  1 -1  1]]
