In [5]:
import numpy as np

1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [6]:
m = np.arange(12).reshape((3,4))

In [7]:
print("This is the total mean:", np.mean(m))

This is the total mean: 5.5


In [8]:
print("Mean of row 1:", np.mean(m[0]))
print("Mean of row 2:", np.mean(m[1]))
print("Mean of row 3:", np.mean(m[2]))

Mean of row 1: 1.5
Mean of row 2: 5.5
Mean of row 3: 9.5


In [9]:
print("Mean of column 1:", np.mean(m[:,0]))
print("Mean of column 2:", np.mean(m[:,1]))
print("Mean of column 3:", np.mean(m[:,2]))
print("Mean of column 4:", np.mean(m[:,3]))

Mean of column 1: 4.0
Mean of column 2: 5.0
Mean of column 3: 6.0
Mean of column 4: 7.0


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [21]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

In [22]:
outer_func = np.outer(u,v)
print(outer_func)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [28]:
list_comp = np.array([(i*j) for i in u for j in v])
print(list_comp.reshape(4,4))

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [35]:
broadcast = u[:, np.newaxis] * v
print(broadcast)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [61]:
a = np.random.uniform(0,3,60)
print(a)

[1.87758541 0.17921537 0.99563968 1.97343177 1.63982983 0.5906275
 1.88062658 0.00612604 2.92868729 1.56829116 1.16986922 1.88799957
 0.50723426 0.02442315 1.98321821 1.4942331  2.27441251 2.96964669
 2.76534618 1.14097774 0.81773949 1.23489399 0.6232028  0.70212104
 0.8312628  0.84737227 0.54992752 2.38196763 1.06356998 2.9109933
 0.44681628 1.37226528 2.64504229 2.46808309 2.56129006 1.18623542
 2.73454563 2.65580647 1.14037119 2.04901526 1.31391696 2.87331117
 2.9039392  2.6742203  1.73700169 2.60441517 0.23805186 0.75269281
 0.18474368 2.76409394 1.78055313 0.4883904  2.28413467 1.2280403
 2.56729331 1.92262159 1.52588931 1.02041769 1.6335444  2.72796587]


In [62]:
mask = a < 0.3
a[mask] = 0
print(a)

[1.87758541 0.         0.99563968 1.97343177 1.63982983 0.5906275
 1.88062658 0.         2.92868729 1.56829116 1.16986922 1.88799957
 0.50723426 0.         1.98321821 1.4942331  2.27441251 2.96964669
 2.76534618 1.14097774 0.81773949 1.23489399 0.6232028  0.70212104
 0.8312628  0.84737227 0.54992752 2.38196763 1.06356998 2.9109933
 0.44681628 1.37226528 2.64504229 2.46808309 2.56129006 1.18623542
 2.73454563 2.65580647 1.14037119 2.04901526 1.31391696 2.87331117
 2.9039392  2.6742203  1.73700169 2.60441517 0.         0.75269281
 0.         2.76409394 1.78055313 0.4883904  2.28413467 1.2280403
 2.56729331 1.92262159 1.52588931 1.02041769 1.6335444  2.72796587]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [70]:
k = np.linspace(0,2*np.pi,100)
print(k)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [71]:
print("Every 10th element of k :", k[0:100:10])

Every 10th element of k : [0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664]


In [73]:
print("Array k reversed:", k[::-1])

Array k reversed: [6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644 1.45972992 1.3962634
 1.33279688 1.26933037 1.20586385 1.14239733 1.07893081 1.01546429
 0.95199777 0.88853126 0.82506474 0.76159822 0

In [75]:
filter = abs(np.sin(k)-np.cos(k)) < 0.1
print(k[filter])

[0.76159822 0.82506474 3.87145761 3.93492413]


5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [87]:
u = np.arange(1,11)
v = np.arange(1,11)
h = np.outer(u,v)
print(h)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [90]:
print("Trace of 10x10 matrix h:", np.trace(h))

Trace of 10x10 matrix h: 385


In [106]:
a = np.flipud(h)
print("Anti-diagonal matrix:", np.diag(a))

Anti-diagonal matrix: [10 18 24 28 30 30 28 24 18 10]


In [108]:
print("Diagonal offset by 1 upwards:", np.diag(h, k = 1))

Diagonal offset by 1 upwards: [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [198]:
init = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
broadcast = abs(init - init[:, np.newaxis])
print(broadcast)

#Converting distances to km:
broadcast_km = broadcast * 1.609344
print(np.round(broadcast_km,2))

[[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
[[   0.    318.65  487.63 1184.48 1401.74 1890.98 2373.78 2484.83 3078.68
  3939.67]
 [ 318.65    0.    168.98  865.83 1083.09 1572.33 2055.13 2166.18 2760.02
  3621.02]
 [ 487.63  168.98    0.    696.85  914.11 1403.35 1886.15 1997.2  2591.04
  3452.04]
 [1184.48  865.83  696.85    0.    217.26  706.5  1189.31 1300.35 1894.2
  2755.2 ]
 [1401.74 1083.09  914.11  217.26    0.    489.24  972.04 1083.09 1676.94
  2537.94]
 [1890.98 1572.33 1403.35  706.5   489.24    

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [147]:
def prime_or_not(x):
    if x < 2:
        return False
    
    for i in range(2, int(np.sqrt(x)) + 1):
        if x % i == 0:
            return False
    return True

def prime_numbers(N):
    numbers = np.array([i for i in range(N+1) if prime_or_not(i)])
    return numbers
    
N = 99
print(prime_numbers(N))

%timeit prime_numbers(10)
%timeit prime_numbers(100)
%timeit prime_numbers(1000)

#The function scales almost linearly with N

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
13.5 µs ± 66.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
144 µs ± 962 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.56 ms ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [151]:
def sieve_of_eratosthenes(n):
    is_prime = np.ones((n+1,), dtype=bool)
    
    is_prime[:2] = False
    
    
    for num in range(2, int(np.sqrt(n)) + 1):
        if is_prime[num] == True:
            is_prime[num*num : n+1 : num] = False
    
    primes = np.nonzero(is_prime)[0]
    return primes


N = 99
print(sieve_of_eratosthenes(N))


[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [152]:
import numpy.random as npr

In [173]:
def walkers(w,s):
    A = npr.randint(-1,2, size=(w, s)) # with npr.randint it is not possible to only get -1 or 1, you generate a range [-1,1]
    #A = npr.choice([-1, 1], size=(w, s)) #This would be the code to generate the matrix only with -1 or 1, but this is not the randint function as described in the exercise. 
    num_rows, num_cols = A.shape
    
    dist_each_walk = np.zeros(w)
    for i in range(num_rows):
        dist_each_walk[i] = sum(A[i,:])
    
    #square_dist = np.square(dist_each_walk)
    square_dist = np.square(A)
    
    mean_each_step = np.zeros(s)
    for i in range(num_cols):
        mean_each_step[i] = np.mean(A[:,i])
    
    #print(dist_each_walk)
    #print(mean_each_step)

print(walkers(1000,200))

[[ 1  1 -1 -1  1]
 [-1  1 -1  1 -1]
 [-1  1  1  1 -1]
 [-1  1  1  1  1]
 [-1 -1  1  1 -1]
 [-1  1  1  1  1]
 [-1  1  1  1  1]
 [ 1 -1  1 -1  1]
 [ 1 -1 -1  1  1]
 [ 1  1 -1 -1 -1]]
None
