1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [1]:
import numpy as np

In [7]:
m = np.arange(12).reshape((3,4))
print(m)

print('Total mean',m.mean())
print('Mean for each col',m.mean(axis=0))
print('Mean for each row',m.mean(axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Total mean 5.5
Mean for each col [4. 5. 6. 7.]
Mean for each row [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [37]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print('u =',u)
print('v =',v)

print('\nusing the function outer in numpy\n',np.outer(u,v))
print('\nusing a nested for loop or a list comprehension')
matrix = []
for i in range(len(u)):
    for j in range(len(v)):
        matrix.append(u[i]*v[j])
    
    
A = np.array(matrix).reshape(len(u),len(v))
print(A)

u = u[:,np.newaxis]
print('\nusing numpy broadcasting operations\n',u*v)


u = [1 3 5 7]
v = [2 4 6 8]

using the function outer in numpy
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

using a nested for loop or a list comprehension
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

using numpy broadcasting operations
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [59]:
import numpy.random as npr
A = npr.uniform(low=0.0, high=3.0, size=(10,6))
print('10 x 6 matrix with rand values between 0 and 3\n',A)
mask =(A<0.3)
A[A<0.3]=0
print('\n10 x 6 matrix modified\n',A)

10 x 6 matrix with rand values between 0 and 3
 [[0.79414838 2.68535432 0.8777352  1.74026955 0.49502241 0.69660296]
 [2.70127325 2.70153393 1.01594228 1.15312459 1.65594374 0.02928435]
 [0.09183818 2.70424872 0.1555854  1.92061516 0.9051455  2.83417267]
 [0.50287467 2.41710119 0.56227129 0.08463361 1.23007706 1.89602801]
 [1.42788942 0.77051513 0.52702227 2.12820996 0.13752742 0.46072559]
 [0.22586437 1.39265942 0.37314035 0.31987362 2.55746184 1.15123007]
 [2.8635347  2.74727074 0.27326997 2.5057608  0.70745611 2.85698726]
 [2.45414689 2.53191301 0.92125293 1.99829445 2.17555417 2.05591901]
 [0.79463039 0.18711974 1.74032381 2.59431773 0.10838246 2.76202494]
 [2.39025433 1.84473636 2.79019915 0.19511983 2.35847782 2.47104787]]

10 x 6 matrix modified
 [[0.79414838 2.68535432 0.8777352  1.74026955 0.49502241 0.69660296]
 [2.70127325 2.70153393 1.01594228 1.15312459 1.65594374 0.        ]
 [0.         2.70424872 0.         1.92061516 0.9051455  2.83417267]
 [0.50287467 2.41710119 0.562

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)