1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [2]:
import numpy as np
import math
import timeit

m = np.arange(12).reshape((3,4))
print("Media di m: ", m.mean())
print("Media delle colonne di m: ", m.mean(0))
print("Media delle righe di m: ", m.mean(1))

Media di m:  5.5
Media delle colonne di m:  [4. 5. 6. 7.]
Media delle righe di m:  [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [3]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("Outer product with np.outer:\n", np.outer(u,v))
for_outer = np.zeros((len(u), len(v)))
for i in range(len(u)):
    for j in range(len(v)):
        for_outer[i, j]=u[i]*v[j]
print("Outer product with for:\n", for_outer)
tiled_u = np.tile(u, (len(u), 1))
tiled_v = np.tile(v, (len(v), 1))
tiled_outer = tiled_v*tiled_u.T
print("Outer product with numpy.tile:\n", tiled_outer)

Outer product with np.outer:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Outer product with for:
 [[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]
Outer product with numpy.tile:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [4]:
a = 3*np.random.rand(10, 6)
mask = (a>0.3)
print(a[mask])

[2.26718582 1.45614075 2.44977771 2.74498427 1.82673089 1.92343709
 0.50791068 2.63906522 1.16572303 1.66447656 0.36024442 2.74819952
 1.22436384 1.04040772 0.78357386 0.90757475 1.26130507 2.59159379
 0.32921357 2.80791727 2.00356885 0.40379178 0.407955   2.71404667
 0.53816866 0.77391618 2.917097   2.85048255 0.38610375 0.45999628
 2.94095677 0.81203061 1.82240306 2.91937872 2.39964945 2.36944847
 0.5170603  0.36348764 0.53271297 1.78740166 2.80764256 1.72687825
 1.60410263 0.72864629 2.90590095 0.91003612 2.70845345 1.67502096
 0.96781568 1.62634153 2.76035837 0.41043327 1.18342687 2.35685544
 2.87680946]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [5]:
a = np.linspace(0, 2*math.pi, 100)
print("Every 10th element:\n", a[::10],"\n")
print("Reverse array:\n", a[::-1], "\n")
mask = (np.sin(a) - np.cos(a)<0.1)
print("Element for which sin(a)-cos(a)<0.1:\n", a[mask])

Every 10th element:
 [0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664] 

Reverse array:
 [6.28318531 6.21971879 6.15625227 6.09278575 6.02931923 5.96585272
 5.9023862  5.83891968 5.77545316 5.71198664 5.64852012 5.58505361
 5.52158709 5.45812057 5.39465405 5.33118753 5.26772102 5.2042545
 5.14078798 5.07732146 5.01385494 4.95038842 4.88692191 4.82345539
 4.75998887 4.69652235 4.63305583 4.56958931 4.5061228  4.44265628
 4.37918976 4.31572324 4.25225672 4.1887902  4.12532369 4.06185717
 3.99839065 3.93492413 3.87145761 3.8079911  3.74452458 3.68105806
 3.61759154 3.55412502 3.4906585  3.42719199 3.36372547 3.30025895
 3.23679243 3.17332591 3.10985939 3.04639288 2.98292636 2.91945984
 2.85599332 2.7925268  2.72906028 2.66559377 2.60212725 2.53866073
 2.47519421 2.41172769 2.34826118 2.28479466 2.22132814 2.15786162
 2.0943951  2.03092858 1.96746207 1.90399555 1.84052903 1.77706251
 1.71359599 1.65012947 1.58666296 1.52319644 

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [6]:
table = np.zeros((10, 10), "int")
for i in range(1, 11):
    table[i-1] = np.arange(i, 11*i, i)
print(table, "\n")
print("Trace of that matrix: ", np.trace(table), "\n")
anti_diag=[]
for j in range(table.shape[1]):
    anti_diag.append(table[j, table.shape[1]-1-j])
print("Anti diagonal:", anti_diag)
diag2=[]
for c in range(table.shape[1]-1):
    diag2.append(table[c,c+1])
print("\nDiagonal with offset 1:", diag2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] 

Trace of that matrix:  385 

Anti diagonal: [10, 18, 24, 28, 30, 30, 28, 24, 18, 10]

Diagonal with offset 1: [2, 6, 12, 20, 30, 42, 56, 72, 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [10]:
cities = ["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]
distances = [0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448]
grid = np.zeros((len(cities), len(cities)))
for i in range(len(cities)):
    for j in range(i + 1, len(cities)):
        grid[i][j] = distances[j]-distances[i]
        grid[j][i] = grid[i][j]
print("Grid in miles:\n", grid)
KMgrid=grid*0.6213712
print("\nGrid in km:\n", KMgrid)

Grid in miles:
 [[   0.  198.  303.  736.  871. 1175. 1475. 1544. 1913. 2448.]
 [ 198.    0.  105.  538.  673.  977. 1277. 1346. 1715. 2250.]
 [ 303.  105.    0.  433.  568.  872. 1172. 1241. 1610. 2145.]
 [ 736.  538.  433.    0.  135.  439.  739.  808. 1177. 1712.]
 [ 871.  673.  568.  135.    0.  304.  604.  673. 1042. 1577.]
 [1175.  977.  872.  439.  304.    0.  300.  369.  738. 1273.]
 [1475. 1277. 1172.  739.  604.  300.    0.   69.  438.  973.]
 [1544. 1346. 1241.  808.  673.  369.   69.    0.  369.  904.]
 [1913. 1715. 1610. 1177. 1042.  738.  438.  369.    0.  535.]
 [2448. 2250. 2145. 1712. 1577. 1273.  973.  904.  535.    0.]]

Grid in km:
 [[   0.         123.0314976  188.2754736  457.3292032  541.2143152
   730.11116    916.52252    959.3971328 1188.6831056 1521.1166976]
 [ 123.0314976    0.          65.243976   334.2977056  418.1828176
   607.0796624  793.4910224  836.3656352 1065.651608  1398.0852   ]
 [ 188.2754736   65.243976     0.         269.0537296  352.9388416
  

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [10]:
def measure_time(func):
    def wrapper(*args, **kwargs):
        Tstart = timeit.default_timer()
        result = func(*args, **kwargs)
        Tend = timeit.default_timer()
        Texec = Tend - Tstart
        print("This function took {:.6f} seconds to run.".format(Texec))
        return result
    return wrapper

@measure_time
def prime_n(array):
    primes = []
    for x in array:
        if x==1 or x==0:
            is_prime=False
        else:
            is_prime=True
        for i in range(2, int(x/2)+1):
            if x % i == 0:
                is_prime = False
        if is_prime:
            primes.append(x)
    return primes

@measure_time
def sieve_prime(array):
    max_num = max(array)
    sieve = np.ones(max_num + 1, dtype=bool)
    sieve[:2] = False
    for n in range(2, int(np.sqrt(max_num)) + 1):
        if sieve[n]:
            sieve[n * n::n] = False
    return array[sieve]
    
N=2000
numbers = np.arange(N)
print("Prime numbers:\n", prime_n(numbers), "\n")
print("Prime numbers using sieve of eratosthenes:\n", sieve_prime(numbers))

'''
The time of execution of the function prime_n grows with proportion to N^2 (with N=100 the time is 0.000641, with N=1000 is 0.057 and with N=2000 is 0.237), while sieve_prime's execution time is almost linear in the dimension of N (with N=100 the time is 0.000076, with N=1000 is 0.000108 and with N=2000 is 0.000199).
'''


This function took 0.248066 seconds to run.
Prime numbers:
 [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013, 1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069, 1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 11

"\nThe time of execution of the function prime_n grows with proportion to N^2 (with N=100 the time is 0.000641, with N=1000 is 0.057 and with N=2000 is 0.237), while sieve_prime's execution time is almost linear in the dimension of N (with N=100 the time is 0.000076, with N=1000 is 0.000108 and with N=2000 is 0.000199).\n"

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [11]:
walkers, times = 1000, 200
steps = np.random.randint(2, size=(walkers, times))*2-1
progress = np.zeros(steps.shape, "int")
for i in range(walkers):
    for j in range(times):
        progress[i, j]=progress[i, j-1]+steps[i, j]
print("Total walked distance of each walker:\n", progress[:, times-1])
square_prog = progress * progress
mean_step=np.zeros(times)
for c in range(times):
    mean_step[c]=sum(square_prog[:, c])/walkers
print("\nMean of squared distances at each time's step:\n", mean_step)

Total walked distance of each walker:
 [  8  14   0  16  -2  22   6 -18  12  22   0  -4 -28   8   8  16  -6  -2
  18  10  22  -4 -22 -14 -12 -18   6   8   0  14  -2 -10  16 -26  30 -28
 -14 -24  -4   8  20 -26 -20   4   8   8 -16   6  14  14   2  14   6  -6
 -14  28  -8   4  24  16   0   2  -6 -26  22  16  -4 -10   8   0 -32 -20
   2  -4   2   8  -4   0  28   0 -28   6  -2   8   2   2 -14  18  34   8
  14 -14   6  14   6  28   2   0   4  -8   6  12  14  -4  10 -20   8   6
 -20  -2   2 -10  10  -4   8  12 -12  26   2  18  -8   4  20  -4   2  16
   4  -4 -30  14   8   6  22  20  -2  -2  -4  24 -22  -6  -8 -12   6  12
 -10  14   4 -22 -12   6  -8 -14  16  30   8  14  18   4  -6  14  -2 -10
  -4   6   6  16  32  -4   6   6  -4  24   4 -36 -12  30 -18   6  -4   4
   4  12  18  30  10  -8   6   0   6 -10 -10 -12   8  20  -2 -12  -2 -10
 -18   4  12   6 -26 -14 -26   2   8   6  -2  -2  12  16 -22  12   8  12
  14  28 -14  -6 -16  -8   4  -2  22  14  28   6  10  -8  16  20  14  12
   6 -22  20