1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [2]:
import numpy as np
m = np.arange(12).reshape((3, 4))
print(m)
total_mean = np.mean(m)
row_mean = np.mean(m, axis=1)
column_mean = np.mean(m, axis=0)

print(f"total mean is {total_mean},the mean for each row is {row_mean},the mean for each column is{column_mean}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
total mean is 5.5,the mean for each row is [1.5 5.5 9.5],the mean for each column is[4. 5. 6. 7.]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [3]:
import numpy as np

u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# 1. Using the function `outer` in numpy
outer_np = np.outer(u, v)
print(outer_np)

# 2. Using a nested `for` loop or a list comprehension
demo = []
for x in range(len(u)):
    temp = []
    for y in range(len(v)):
        temp.append(u[x]*v[y])
    demo.append(temp)

list_outer = np.array(demo)
print(list_outer)

#qs: how to use list comprehension to write the list
# outer_list = np.array([u[x]*v[y]]for x in range(len(u)) for y in range(len(v)) if y == 4)
# print(outer_list)

# 3. Using numpy broadcasting operations
u2 = u.reshape(-1, 1) 
uu = np.repeat(u2, 4, axis=1) 
uuv_ba = uu*v
print(uuv_ba)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [4]:
import numpy as np

a = np.random.uniform(0, 3, [6, 10]) 
print(a, '\n')

a[a < 0.3] = 0

print(f"the result of using mask is {a}")

[[0.04504711 0.46529878 2.25657679 0.25645128 1.88072448 1.742358
  0.17113353 1.41921401 1.78181857 0.17738318]
 [0.56745579 2.04775611 1.8069668  0.4502331  2.71770725 0.75518107
  0.02084841 0.37686583 1.51783929 1.65614654]
 [1.80086593 2.38558602 2.99751681 1.86808687 2.03909733 0.76882947
  2.97680803 0.79105878 2.93617786 2.14236794]
 [1.43019614 1.36338305 0.2966765  1.3694582  2.59121673 2.48982192
  2.0250341  0.07145009 1.28464571 0.63088999]
 [0.51158596 1.00808514 1.65552102 0.02204705 2.69557202 1.13575489
  0.16561941 0.66480825 2.88380791 2.66736543]
 [0.07204205 0.41606003 2.85477604 0.69680804 2.72753638 0.16603845
  1.56700323 1.73011358 0.21045081 0.42631215]] 

the result of using mask is [[0.         0.46529878 2.25657679 0.         1.88072448 1.742358
  0.         1.41921401 1.78181857 0.        ]
 [0.56745579 2.04775611 1.8069668  0.4502331  2.71770725 0.75518107
  0.         0.37686583 1.51783929 1.65614654]
 [1.80086593 2.38558602 2.99751681 1.86808687 2.03909

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [8]:
import numpy as np
import matplot.pyplot as plt

# np.linspace(tart, stop, num=50, endpoint=True, retstep=False, dtype=None)
tri = np.linspace(0, 2 / np.pi, num=100, endpoint=True)

#Extract every 10th element using the slice notation
tri_ten =np.split(tri, 10)
tt = tri[::10]

print(tri_ten)

#Reverse the array using the slice notation
res = tri[::-1]
print(res)

#Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is < 0.1
mask = (abs(np.sin(tri) - np.cos(tri) < 0.1))
tri[mask]

#Optional**: make a plot showing the sin and cos functions and indicate where they are close
sin = np.sin(tri)
cos = np.cos(tri)
plt.plot(tri, sin, tri, cos)
plt.title("plot of the sin and cos")


ModuleNotFoundError: No module named 'matplot'

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [9]:
import numpy as np


def mult_table(n):
    temp = np.arange(1, n + 1)
    print(temp, temp[:, None])
    return temp * temp[:, None]


mult_ten = mult_table(10)

mat_trace = np.trace(mult_ten)

anti_diag = np.fliplr(mult_ten).diagonal()

up_diag = np.diagonal(mult_ten, offset=1)
print(f"the 10 by 10 multiplication table\n{mult_ten}\n"
      f"the trace of the matrix\n{mat_trace}\n"
      f"the anti-diagonal matrix\n{anti_diag}\n "
      f"the diagonal offset by 1 upwards \n{up_diag} ")

[ 1  2  3  4  5  6  7  8  9 10] [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
the 10 by 10 multiplication table
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
the trace of the matrix
385
the anti-diagonal matrix
[10 18 24 28 30 30 28 24 18 10]
 the diagonal offset by 1 upwards 
[ 2  6 12 20 30 42 56 72 90] 


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [11]:
import numpy as np
miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

dist_miles = np.abs(miles - miles[:, np.newaxis])

# print("Distance in miles: \n", dist_miles)
print(miles[:, np.newaxis])

dist_km = dist_miles * 1.60934
print("\nDistance in km: \n", dist_km.round())

[[   0]
 [ 198]
 [ 303]
 [ 736]
 [ 871]
 [1175]
 [1475]
 [1544]
 [1913]
 [2448]]

Distance in km: 
 [[   0.  319.  488. 1184. 1402. 1891. 2374. 2485. 3079. 3940.]
 [ 319.    0.  169.  866. 1083. 1572. 2055. 2166. 2760. 3621.]
 [ 488.  169.    0.  697.  914. 1403. 1886. 1997. 2591. 3452.]
 [1184.  866.  697.    0.  217.  707. 1189. 1300. 1894. 2755.]
 [1402. 1083.  914.  217.    0.  489.  972. 1083. 1677. 2538.]
 [1891. 1572. 1403.  707.  489.    0.  483.  594. 1188. 2049.]
 [2374. 2055. 1886. 1189.  972.  483.    0.  111.  705. 1566.]
 [2485. 2166. 1997. 1300. 1083.  594.  111.    0.  594. 1455.]
 [3079. 2760. 2591. 1894. 1677. 1188.  705.  594.    0.  861.]
 [3940. 3621. 3452. 2755. 2538. 2049. 1566. 1455.  861.    0.]]


7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [12]:
import timeit
import numpy as np
a = np.random.randint(0, 9, 15) # 15 random int between 0 and 21
print("original array:", a, '\n')

# create a mask to filter multiples of 3
mask = (a % 3 == 0)
print("the mask:", mask, '\n')

filtered_a = a[mask]
# equivalent to a[a % 3 == 0]
print("the filtered array:", filtered_a, '\n')

# verify that fancy indexing creates copies
print("are a and filtered_a the same object?", np.may_share_memory(a, filtered_a), '\n')

# Indexing with a mask can be very useful to assign a new value to a sub-array
a[a % 3 == 0] = -1
print("the modified array:", a, '\n')


N = np.arange(2, 100)
for i in range(98):
    if(N[i] != False):
        for j in range(i + 1, 98):
            if(N[j] % N[i] == 0):
                N[j] = False
mask = (N != 0)
filtered = N[mask]
print("Prime numbers\n", filtered)

def SieveOfEratosthenes(n):
    prime = [True for i in range(n + 1)]
    p = 2
    while (p * p <= n):

        if (prime[p] == True):

            for i in range(p ** 2, n + 1, p):
                prime[i] = False
        p += 1

    prime[0] = False
    prime[1] = False

    for p in range(n + 1):
        if prime[p]:
            print(p)

starttime = timeit.default_timer()
SieveOfEratosthenes(1000)
print("The time difference is :", timeit.default_timer() - starttime)

original array: [1 4 1 3 4 8 0 5 1 6 6 6 0 6 0] 

the mask: [False False False  True False False  True False False  True  True  True
  True  True  True] 

the filtered array: [3 0 6 6 6 0 6 0] 

are a and filtered_a the same object? False 

the modified array: [ 1  4  1 -1  4  8 -1  5  1 -1 -1 -1 -1 -1 -1] 

Prime numbers
 [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
91

8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [13]:
import numpy as np

walkers = np.random.randint(0, 2, size=(10, 2))
walkers = walkers * 2 - 1
# dataset = np.asarray(walkers)
# dataset = dataset * 2 -1
print(walkers)
# row_sum = np.sum(walkers, axis=0)
# squ_ary = np.square(row_sum)
# column_mean = np.mean(walkers, axis=0)
# print(f"2D array of size walkers * steps\n{walkers}\n"
#       f"the walking distances for each walker by summing the elements in each row\n{row_sum}\n"
#       f"the square of the previously-obtained array\n{squ_ary}\n"
#       f"the mean of the squared distances at each step\n{column_mean}\n"
#       )


[[ 1  1]
 [ 1  1]
 [ 1 -1]
 [ 1 -1]
 [-1 -1]
 [-1 -1]
 [ 1  1]
 [ 1 -1]
 [ 1  1]
 [-1 -1]]
