1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [4]:
import numpy as np

m = np.arange(12).reshape((3,4))

print(m)

avg = 0
avgRow = 0
avgCol = 0

avg = sum(sum(m))/(m.shape[0]*m.shape[1])
print("Mean : ",avg)

avg = np.mean(m)
print("Mean : ",avg)

for i in range(m.shape[0]):
    avgRow = sum(m[i])/len(m[i])
    print("Mean on rows ",i," : ",avgRow)

for i in range(m.shape[1]):
    avgCol = sum(np.transpose(m)[i])/len(np.transpose(m)[i])
    print("Mean on columns ",i," : ",avgCol)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean :  5.5
Mean :  5.5
Mean on rows  0  :  1.5
Mean on rows  1  :  5.5
Mean on rows  2  :  9.5
Mean on columns  0  :  4.0
Mean on columns  1  :  5.0
Mean on columns  2  :  6.0
Mean on columns  3  :  7.0


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [5]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

m = np.outer(u,v)
print(m)

m = np.array([[i*j for i in u]for j in v])
print(m)

m = u[:,np.newaxis]*v
print(m)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[ 2  6 10 14]
 [ 4 12 20 28]
 [ 6 18 30 42]
 [ 8 24 40 56]]
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [6]:
m = np.random.uniform(0,3,size=(10,6))
print(m)
mask = m<.3
m[mask] = 0
print(m)

[[0.37202675 2.50676947 0.08913181 1.9770013  2.04885153 0.62135004]
 [0.16844632 2.30265511 2.3162986  1.05010265 2.00443096 1.65612969]
 [0.01015664 1.071942   0.31415851 2.17277457 2.68371023 1.52035998]
 [1.79552432 0.35067153 2.76716761 2.31003708 1.6866048  1.93726878]
 [0.25537993 1.761409   2.36875722 0.13683536 2.51051534 1.16710032]
 [0.90417892 1.2776088  1.38820686 1.38326636 1.67297708 2.39755725]
 [0.2468148  0.73154827 0.92821538 0.9444601  2.01814231 2.96591742]
 [0.20427561 0.24997178 1.91867827 2.17663961 2.17905273 0.5946824 ]
 [0.35345156 1.86905571 0.43375814 1.0995653  0.48759913 2.78874626]
 [1.65141718 2.48914073 1.0338583  2.44837041 1.44253378 0.4780845 ]]
[[0.37202675 2.50676947 0.         1.9770013  2.04885153 0.62135004]
 [0.         2.30265511 2.3162986  1.05010265 2.00443096 1.65612969]
 [0.         1.071942   0.31415851 2.17277457 2.68371023 1.52035998]
 [1.79552432 0.35067153 2.76716761 2.31003708 1.6866048  1.93726878]
 [0.         1.761409   2.3687572

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [10]:
m = np.linspace(0,2*np.pi,100)
print(m)
print(m[9::10])
print(m[::-1])
extract = []
for i in m:
    if abs(np.sin(i)-np.cos(i))<.1:
        extract.append(i)
print(extract)
# print([np.cos(i) for i in extract])
# print([np.sin(i) for i in extract])

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [11]:
u = np.arange(1,11)
v = np.arange(1,11)
m = np.outer(u,v)
print(m)
print(np.trace(m))
print(np.diag(m[::-1]))
print(np.diag(m[1:]))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
385
[10 18 24 28 30 30 28 24 18 10]
[ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [12]:
positions_miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
positions_km = positions_miles * 1.60934
grid = np.abs(positions_miles[:, np.newaxis] - positions_miles)
print("Grid in miles")
print(grid)
grid = np.abs(positions_km[:, np.newaxis] - positions_km)
print("Grid in km")
print(grid)

Grid in miles
[[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
Grid in km
[[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47424  865.82492  696.84422    0.       217.2609   706.50026
  1189.30226 1300.34672 1894.193

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [14]:
def prime(nb):
    if nb<2:
        return False
    for i in range(2,nb):
        if nb%i==0:
            return False
    return True

def sieve(m):
    if(len(m)<2):
        return [True for i in range(len(m))]
    mask = [False for i in range(len(m))]
    mask[0] = True
    mask[1] = True
    # mask[:2]=True # Doesn't work, idk why
    for i in range(2,len(m)):
        if(mask[i]):
            continue
        for j in range(i+1,len(m)):
            if(mask[j]):
                continue
            if(m[j]%i==0):
                mask[j]=True
    return(mask)

from time import time

n = 100000
m = np.arange(n+1)
mSieve = np.arange(n+1)
a=time()
mask = [not(prime(i)) for i in m]
b=time()
print(b-a,"secondes for conditional list")
m[mask] = 0
# print(m)
a=time()
maskSieve = sieve(mSieve)
b=time()
print(b-a,"secondes for sieve")
mSieve[maskSieve]=0
# print(mSieve)

26.267868280410767 secondes for conditional list
14.715731859207153 secondes for sieve


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [15]:
walkers = 1000
steps = 200

import numpy.random as npr

m = npr.randint(-1,2,size=(walkers,steps))
mDist = np.arange(walkers)
print(m)
for i in range(walkers):
    dist = m[i].sum()
    mDist[i] = dist
    print("For walker n°",i,"distance =",dist)
mDistSqr = [i**2 for i in mDist]
print(mDistSqr)
for i in range(steps):
    avg = np.transpose(m)[i].sum()/steps
    print("For step n°",i,"mean =",avg)

[[ 1  0  0 ...  1 -1  1]
 [ 0  0 -1 ...  0 -1 -1]
 [ 0  0  0 ...  0 -1  0]
 ...
 [-1  1 -1 ... -1  0  0]
 [ 0  0 -1 ... -1 -1 -1]
 [-1  1  1 ...  1 -1  1]]
For walker n° 0 distance = -4
For walker n° 1 distance = -15
For walker n° 2 distance = 17
For walker n° 3 distance = 1
For walker n° 4 distance = -10
For walker n° 5 distance = -5
For walker n° 6 distance = -2
For walker n° 7 distance = -16
For walker n° 8 distance = -30
For walker n° 9 distance = -10
For walker n° 10 distance = -1
For walker n° 11 distance = 18
For walker n° 12 distance = -11
For walker n° 13 distance = -11
For walker n° 14 distance = -21
For walker n° 15 distance = 12
For walker n° 16 distance = -8
For walker n° 17 distance = 23
For walker n° 18 distance = -30
For walker n° 19 distance = 13
For walker n° 20 distance = 0
For walker n° 21 distance = 13
For walker n° 22 distance = -23
For walker n° 23 distance = 9
For walker n° 24 distance = -3
For walker n° 25 distance = -11
For walker n° 26 distance = -1
For walke