In [1]:
# exercise4 part one.Reductions


import numpy as np # import naming convention

m = np.arange(12).reshape((3,4))
print("matrix is :\n" , m)

# Q1.find the total mean
tot_mean = np.mean(m)
print("\nTotal Mean is:", tot_mean)

# Q2.find the mean for each row and column
# Find and print the mean for each row in the matrix
row = np.mean(m, axis=1)
print("\nMean of Each Rows:", row)
# Print each row
print("\nEach Row:")
for row in m:
    print(row)

# Find and print the mean for each column in the matrix
column = np.mean(m, axis=0)
print("\nMean of Each Columns:", column)
# Print each column
print("\nEach Column:")
for j in range(len(m[0])):
    column = m[:, j]
    print(f"Column {j + 1}: {column}")

matrix is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Total Mean is: 5.5

Mean of Each Rows: [1.5 5.5 9.5]

Each Row:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

Mean of Each Columns: [4. 5. 6. 7.]

Each Column:
Column 1: [0 4 8]
Column 2: [1 5 9]
Column 3: [ 2  6 10]
Column 4: [ 3  7 11]


In [2]:
# exercise4 part two.Outer product


import numpy as np

u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

# Q1.Using outer function
print ("Using the outer function:\n", np.outer(u,v))

# Q2.Using a nested for loop
result = []
for i in u:
    row = []
    for j in v:
        row.append(i * j)
    result.append(row)
print ("\nOuter product using nested loop:\n", np.array(result) )

# Q3.Using numpy broadcasting operations
u_broadcasting = u.reshape(-1, 1)
outer_product_broadcasting = u_broadcasting * v
print("\nOuter product using broadcasting:\n", outer_product_broadcasting)

Using the outer function:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Outer product using nested loop:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Outer product using broadcasting:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [3]:
# exercise 4 part three. Matrix masking


import numpy as np

# Create a 10*6 matrix of random numbers between 0 and 3
matrix_size = (10, 6)
lower_case = 0
upper_case = 3

# Create a random matrix name m using a uniform distribution
m = np.random.uniform(lower_case, upper_case, size=matrix_size)

# Set all elements in the matrix m that are less than 0.3 to zero.m[mask] = 0
m[m<0.3]=0

# Display the matrix
print("Random Matrix with Entries < 0.3 Set to Zero:\n", m)

Random Matrix with Entries < 0.3 Set to Zero:
 [[0.91548729 2.97094868 1.9655692  1.80724266 2.23892782 0.        ]
 [0.         0.52211849 1.08413895 1.55554562 1.06764302 2.36433712]
 [0.89842707 0.         1.45884584 1.65631628 2.7350634  0.46507452]
 [2.63890026 2.00823727 2.3688824  2.74041458 0.36691058 0.61510445]
 [2.20025844 0.66622453 1.27342973 2.4487845  0.         1.55827841]
 [2.79299343 1.20974937 2.54896271 2.34249944 1.85067905 2.50140659]
 [1.90044308 1.0436961  0.83111094 2.95393396 0.73292468 2.88667718]
 [2.45141526 2.16778624 0.66684018 0.9717065  1.70823356 0.84139371]
 [0.46420707 2.43041127 1.25661147 0.9780469  1.51197188 0.81258154]
 [1.20327279 0.         2.15052002 2.70033384 0.50992612 0.844258  ]]


In [4]:
# exercise 4 part four. Trigonometric functions


import numpy as np

# Create an array of 100 numbers
start = 0
stop = 2 * np.pi
num_points = 100  # number of points we want in our array
angles = np.linspace(start, stop, num_points)

# ract every 10th element from the array
alternative = []
for i in range(0, len(angles), 10):
    alternative.append(angles[i])

# Q1.Convert the result back to a NumPy array
convert = np.array(alternative)
print("Every 10th element:\n", convert)

# Q2. Reverse the array using a loop
reversed_angles = []
for j in range(len(angles) - 1, -1, -1):
    reversed_angles.append(angles[j])
print("\nReversed array:\n", reversed_angles)


# Q3.Extract elements where the absolute difference between sin and cos is < 0.1
sin_values = np.sin(angles) # sin value for each angle
cos_values = np.cos(angles) # cos value for each angle

abs_difference = np.abs(sin_values - cos_values) # Calculate the difference between sin and cos
close_points = angles[abs_difference < 0.1] # Select elements where the difference is less than 0.1
print("\nClose points between sin and cos:\n", close_points)

Every 10th element:
 [0.         0.63466518 1.26933037 1.90399555 2.53866073 3.17332591
 3.8079911  4.44265628 5.07732146 5.71198664]

Reversed array:
 [6.283185307179586, 6.219718788925247, 6.156252270670908, 6.092785752416569, 6.029319234162229, 5.96585271590789, 5.902386197653551, 5.838919679399211, 5.775453161144872, 5.711986642890533, 5.648520124636194, 5.585053606381854, 5.521587088127515, 5.458120569873176, 5.394654051618837, 5.331187533364497, 5.267721015110158, 5.204254496855819, 5.14078797860148, 5.07732146034714, 5.013854942092801, 4.950388423838462, 4.886921905584122, 4.823455387329783, 4.759988869075444, 4.696522350821105, 4.6330558325667655, 4.569589314312426, 4.506122796058087, 4.442656277803748, 4.3791897595494085, 4.3157232412950695, 4.25225672304073, 4.188790204786391, 4.1253236865320515, 4.0618571682777125, 3.998390650023373, 3.934924131769034, 3.8714576135146945, 3.8079910952603555, 3.744524577006016, 3.681058058751677, 3.6175915404973376, 3.5541250222429985, 3.4906

In [5]:
# exercise 4 part five.Matrices


import numpy as np

# Create an empty list to store the rows
table_list = []

# Use nested loops to fill the list.
for i in range(10):
    row = []
    for j in range(10):
        row.append((i + 1) * (j + 1))
    table_list.append(row)

# Convert the list to a NumPy array
multiplication_table = np.array(table_list, dtype=int)

# Display the multiplication table matrix
print("\nMultiplication Table Matrix:")
print(multiplication_table)

# Fill in the matrix with multiplication table values
for i in range(1, 11):
    for j in range(1, 11):
        multiplication_table[i-1, j-1] = i * j

# Display the multiplication table matrix
print("\n\nMultiplication Table Matrix:", multiplication_table)

# Q1.Find the trace of the matrix
trace_value = np.trace(multiplication_table)
print("\n\nTrace of the Matrix:", trace_value)

# Q2.Extract the anti-diagonal matrix
anti_diagonal = np.flipud(multiplication_table)
print("\n\nAnti-Diagonal Matrix:", anti_diagonal)

# Q3.Extract the diagonal offset by 1 upwards
diagonal_offset = np.diagonal(multiplication_table, offset=1)
print("\n\nDiagonal Offset by 1 Upwards:" , diagonal_offset)


Multiplication Table Matrix:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Multiplication Table Matrix: [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Trace of the Matrix: 385


Anti-Diagonal Matrix: [[ 10  20  30  40  50  60 

In [6]:
#exercise4 part six.Broadcasting


import numpy as np

# Cities along Route 66
cities = ["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]

# Corresponding positions in miles
position_miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

# Q1. Build a 2D grid of distances among each city along Route 66
num_cities = len(cities)
distances_alternative = np.zeros((num_cities, num_cities))  # creating arrays of zeros

for i in range(num_cities):
    for j in range(num_cities):
        distances_alternative[i, j] = position_miles[j] - position_miles[i]

# Take the absolute values of the differences
distances_alternative = np.abs(distances_alternative)

# Display the 2D grid of distances in miles
print("2D Grid of Distances (in miles):")
print(distances_alternative)

# Q2. Convert the distances to km
convert_factor = 1.60934

# Convert distances from miles to kilometers
position_km = position_miles * convert_factor

# Create an empty 2D array for distances in kilometers
distances_km = np.zeros((len(position_km), len(position_km)))

# Calculate the absolute differences between each pair of distances and fill the 2D array
for i in range(len(position_km)):
    for j in range(len(position_km)):
        distances_km[i, j] = np.abs(position_km[j] - position_km[i])

# Display the 2D grid of distances in kilometers
print("\n2D Grid of Distances (in kilometers):", distances_km)


2D Grid of Distances (in miles):
[[   0.  198.  303.  736.  871. 1175. 1475. 1544. 1913. 2448.]
 [ 198.    0.  105.  538.  673.  977. 1277. 1346. 1715. 2250.]
 [ 303.  105.    0.  433.  568.  872. 1172. 1241. 1610. 2145.]
 [ 736.  538.  433.    0.  135.  439.  739.  808. 1177. 1712.]
 [ 871.  673.  568.  135.    0.  304.  604.  673. 1042. 1577.]
 [1175.  977.  872.  439.  304.    0.  300.  369.  738. 1273.]
 [1475. 1277. 1172.  739.  604.  300.    0.   69.  438.  973.]
 [1544. 1346. 1241.  808.  673.  369.   69.    0.  369.  904.]
 [1913. 1715. 1610. 1177. 1042.  738.  438.  369.    0.  535.]
 [2448. 2250. 2145. 1712. 1577. 1273.  973.  904.  535.    0.]]

2D Grid of Distances (in kilometers): [[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448


In [7]:
# exercise4 part seven.Prime numbers sieve


import numpy as np
import timeit

# Q1. Construct a shape (N,) boolean array
def  prime_numbers_sieve(n):
    is_prime = [True] * (n + 1)     # Creating a list to keep numbers

    is_prime[0] = is_prime[1] = False

# Q2.Identify the multiples of each number
    for i in range(2, int(np.sqrt(n)) + 1):      # find prime numbers with sieve algorythm
        if is_prime[i]:
            for j in range(i*i, n+1, i):
                is_prime[j] = False

    # Create an empty list to store prime numbers
    primes = []

# Q3.Apply the mask to obtain an array
    # Add prime numbers to the list
    for i in range(n + 1):
        if is_prime[i]:
            primes.append(i)

    # Convert the list to a NumPy array
    primes = np.array(primes)
    return primes

# Set the range upper limit (N)
N = 99

# Use the sieve to find prime numbers
primes =  prime_numbers_sieve(N)

# Display the prime numbers
print("Prime Numbers up to", N, ":", primes)

# Q4.Check the performances (with timeit)
# Check the performance using timeit
lambda_function = lambda: prime_numbers_sieve(N)
time_taken = timeit.timeit(lambda_function, number=10000) # Measure the time taken using timeit with 10000 iterations
print("Time taken for N =", N, ":", time_taken, "seconds")


Prime Numbers up to 99 : [ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]
Time taken for N = 99 : 0.17840010800000528 seconds


In [9]:
# exercise 4 part eight.Diffusion using random walk


import numpy as np
from numpy.random import randint

# Q1. Set the number of walkers and steps
walkers = 1000
steps = 200

# Q2. Create a 2D array for random walk steps
random_steps = randint(low=-1, high=2, size=(walkers, steps))

# Q3. Calculate walking distances for each walker
distances = []      # set a list to store

for current_step in range(1, steps + 1):
    # indexing for rows and columns
    rows = np.arange(walkers)
    columns = np.arange(current_step)

    # Create an empty list to store rows with selected columns
    selected_rows = []

    # Loop through each row in random_steps
    for row in random_steps:
        # Select the desired columns for the current row
        selected_row = row[columns]

        # Append the selected row to the list
        selected_rows.append(selected_row)

    # Convert the list of rows into a NumPy array
    selected_steps = np.array(selected_rows)

    # Sum the steps for each walker
    total_distance = np.sum(selected_steps, axis=1)

    # Store the total distance for each walker at the current step
    distances.append(total_distance)

# Q4.Convert the list of distances into a NumPy array
distances = np.array(distances).T

# Calculate the squared distances
squared_distances = pow(distances, 2)

# Q5.Calculate the average squared distance at each time step
mean_distances = np.mean(squared_distances, axis=0)

# Print the results
print("Average squared distance at each time step:")
print(mean_distances)

Average squared distance at each time step:
[  0.703   1.319   1.977   2.635   3.431   4.011   4.698   5.43    6.052
   6.776   7.466   8.134   8.983   9.826  10.698  11.3    12.107  12.947
  13.477  14.299  14.856  15.854  16.556  17.26   17.712  18.857  19.544
  20.018  20.955  21.633  22.102  22.634  23.261  23.683  24.281  25.21
  26.329  26.942  28.063  28.803  29.959  30.727  31.748  32.261  33.052
  33.582  34.189  35.263  35.681  35.866  37.162  38.323  38.351  39.417
  40.356  41.322  41.656  41.936  42.795  43.997  44.828  45.689  46.508
  46.594  47.5    47.761  49.133  49.708  50.266  50.429  50.955  51.463
  52.039  52.502  53.307  54.025  54.974  55.913  56.517  57.071  57.328
  58.354  58.399  59.157  59.166  59.369  59.901  59.975  59.94   60.326
  61.099  61.687  62.181  62.731  63.613  63.845  64.896  65.64   66.686
  67.379  67.738  68.259  68.775  70.404  71.43   71.81   71.762  72.369
  73.122  73.262  73.458  74.833  75.567  76.767  77.573  78.772  78.647
  78.947