In [2]:
#1
import numpy as np

m=np.arange(12).reshape((3,4))
print(m)
#find total mean
mean1=np.mean(m)
print(mean1)
#find the mean for each row and column
mean2=np.mean(m,axis=0)
print(mean2)
mean3=np.mean(m,axis=1)
print(mean3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [ ]:
#2
import numpy as np

u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#outer
outer1=np.outer(u,v)
print(outer1)

#list comprehension
outer2=[[x*y for x in v] for y in u]
print(outer2)

#broadcasting
outer3 = u[:, np.newaxis] * v
print(outer3)



In [ ]:
#3
import numpy as np
matr=np.random.uniform(low=0.0, high=3.0, size=(10,6))
print(matr)

import numpy.ma as ma
matr=ma.masked_less(matr,0.3)
matr=matr.filled(0)
print(matr)



In [13]:
#4
import numpy as np
import math

arr=np.linspace(0, 2*math.pi, num=100)


#Extract every 10th element using the slice notation
arr=arr[::10]


#reverse
arr=arr[len(arr)-1:0:-1]


#Extract elements
def function(x):
    return np.abs(np.sin(x) - np.cos(x)) < 0.1

arr = np.linspace(0, 2*np.pi, 100)

filtered_arr = arr[function(arr)]

print(filtered_arr)

[0.76159822 0.82506474 3.87145761 3.93492413]


In [39]:
#5
import numpy as np
import math

outer=np.outer(np.arrange(1,11), np.arrange(1,11))
print(outer)

trace= np.trace(outer)
print(trace)

flip=np.fliplr(outer).diagonal()
print(flip)

diagoff=np.diagonal(outer, offset=1)
print(diagoff)

AttributeError: module 'numpy' has no attribute 'arrange'

In [29]:
#6
import numpy as np
import math

cities=["Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", "Albuquerque", "Flagstaff", "Los Angeles"]
miles=np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
km=miles*1.60934
distance=np.abs(km-km[:, np.newaxis])
print(distance)

[[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47424  865.82492  696.84422    0.       217.2609   706.50026
  1189.30226 1300.34672 1894.19318 2755.19008]
 [1401.73514 1083.08582  914.10512  217.2609     0.       489.23936
   972.04136 1083.08582 1676.93228 2537.92918]
 [1890.9745  1572.32518 1403.34448  706.50026  489.23936    0.
   482.802    593.84646 1187.69292 2048.68982]
 [2373.7765  2055.12718 1886.14648 1189.30226  972.04136  482.802
     0.       111.04446  704.89092 1565.88782]
 [2484.82096 2166.17164 1997.19094 1300.34672 1083.08582  593.84646
   111.04446    0.       593.84646 1454.84336]
 [3078.66742 2760.0181  2591.0374  1894.19318 1676.93228 1187.69292
   704.89092  593.84

In [36]:
#7
import numpy as np
import math
import time

def sieve_of_eratosthenes(N):
    boolean=np.ones(N, dtype=bool)
    boolean[0:2]=False
    for i in range(2,int(np.sqrt(N))+1):
        if boolean[i]:
            boolean[i*i:N:i]=False
        
    prime=np.nonzero(boolean)[0]  
    
    return prime


N=99
primes=sieve_of_eratosthenes(N)
print(primes)


[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [38]:
#8
import numpy as np


walkers=1000
steps=200

arr=np.random.randint(low=-1, high=2, size=(walkers,steps))
summ=np.sum(arr,axis=1)
squared=summ**2
mean=np.mean(squared)

146.146
