1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [1]:
# a.

l_int = [i for i in range(11)]
print(f"\nHere is the list of integers used : {l_int}")

# We write the different data in the text file
with open('data_int.txt', 'w') as file:
    for i in l_int:
        file.write(f"{i}\n")

# Document content display
print("\nHere's the data contained in the document displayed with cat\n")
!cat data_int.txt


Here is the list of integers used : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Here's the data contained in the document displayed with cat

0
1
2
3
4
5
6
7
8
9
10


In [2]:
# b.

import numpy as np # import the NUMPY module

m_float = np.random.rand(5, 5)
print(f"\nHere is the matrix of float used : \n{m_float}")

# We write the different data in the text file
with open('data_float.txt', 'w') as file:
    for row in m_float:
        file_row = ' '.join(map(str, row))
        file.write(file_row + '\n')

# Document content display
print("\nHere's the data contained in the document displayed with cat\n")
!cat data_float.txt


Here is the matrix of float used : 
[[0.70722896 0.7319827  0.82627776 0.74467274 0.99803629]
 [0.85613476 0.8954037  0.12228441 0.29734591 0.50317787]
 [0.71643041 0.94353261 0.76893339 0.59758151 0.42884009]
 [0.39793235 0.2774773  0.1031978  0.24768914 0.02170648]
 [0.75017857 0.95863961 0.6404564  0.10300646 0.80544958]]

Here's the data contained in the document displayed with cat

0.7072289564219554 0.7319827004753666 0.8262777589767234 0.744672738662739 0.9980362930729886
0.8561347637291286 0.8954037006161716 0.12228441123445988 0.29734590892489277 0.5031778709234682
0.7164304080758693 0.9435326056446276 0.7689333874017799 0.5975815068537897 0.4288400864526234
0.3979323530220594 0.2774773007809196 0.10319779601367318 0.24768914441023193 0.021706479220605424
0.7501785723197045 0.9586396107114523 0.6404563964107242 0.10300646100724697 0.8054495791002674


In [3]:
# c.

import pandas as pd # import the PANDAS module

# Load data_float.txt
m_float2 = np.loadtxt('data_float.txt')
print(f"\nHere is the matrix of float loaded thanks to loadtxt : \n{m_float}")

# Convert in dataframe
df = pd.DataFrame(m_float2, columns = ["matrix1", "matrix2", "matrix3", "matrix4", "matrix5"])

# We write the different data in the csv file
with open('data_float.csv', 'w') as file:
    header = ';'.join(map(str, df.columns))
    file.write(header + '\n')

    for index, row in df.iterrows():
        line = ';'.join(map(str, row))
        file.write(line + '\n')

# Document content display
print("\nHere's the data contained in the document displayed with cat\n")
!cat data_float.csv


Here is the matrix of float loaded thanks to loadtxt : 
[[0.70722896 0.7319827  0.82627776 0.74467274 0.99803629]
 [0.85613476 0.8954037  0.12228441 0.29734591 0.50317787]
 [0.71643041 0.94353261 0.76893339 0.59758151 0.42884009]
 [0.39793235 0.2774773  0.1031978  0.24768914 0.02170648]
 [0.75017857 0.95863961 0.6404564  0.10300646 0.80544958]]

Here's the data contained in the document displayed with cat

matrix1;matrix2;matrix3;matrix4;matrix5
0.7072289564219554;0.7319827004753666;0.8262777589767234;0.744672738662739;0.9980362930729886
0.8561347637291286;0.8954037006161716;0.12228441123445988;0.29734590892489277;0.5031778709234682
0.7164304080758693;0.9435326056446276;0.7689333874017799;0.5975815068537897;0.4288400864526234
0.3979323530220594;0.2774773007809196;0.10319779601367318;0.24768914441023193;0.021706479220605424
0.7501785723197045;0.9586396107114523;0.6404563964107242;0.10300646100724697;0.8054495791002674


2\. **JSON files**

Load the file `user_data.json`, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [4]:
#!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json  -P data/

import json # import the JSON module

filename = './data/user_data.json'
data = json.load(open(filename))

# Display of ID and credit card type for each user before filtering
print("\nData before applying the filter :\n")
for user in data:
    print(f"ID: {user['ID']}, CreditCardType: {user['CreditCardType']}")

# Data filtering for credit card type set to "American Express"
filtered_data = [user for user in data if user['CreditCardType'] == 'American Express']

# Display of ID and credit card type for each user after filtering
print("\nData after applying the filter :(American Express only) :\n")
for user in filtered_data:
    print(f"ID: {user['ID']}, CreditCardType: {user['CreditCardType']}")

# Save filtered data
pd.DataFrame(filtered_data).to_csv('filtered_data.csv', index=False)
    
# Document content display
print("\nHere's the data contained in the document displayed with cat\n")
!cat filtered_data.csv


Data before applying the filter :

ID: 1, CreditCardType: Capital One
ID: 2, CreditCardType: American Express
ID: 3, CreditCardType: Discover
ID: 4, CreditCardType: Discover
ID: 5, CreditCardType: Citibank
ID: 6, CreditCardType: MasterCard
ID: 7, CreditCardType: MasterCard
ID: 8, CreditCardType: Discover
ID: 9, CreditCardType: Maestro
ID: 10, CreditCardType: Bank of America
ID: 11, CreditCardType: MasterCard
ID: 12, CreditCardType: American Express
ID: 13, CreditCardType: MasterCard
ID: 14, CreditCardType: Maestro
ID: 15, CreditCardType: Discover
ID: 16, CreditCardType: Citibank
ID: 17, CreditCardType: Maestro
ID: 18, CreditCardType: Maestro
ID: 19, CreditCardType: Chase
ID: 20, CreditCardType: Discover
ID: 21, CreditCardType: Visa
ID: 22, CreditCardType: Citibank
ID: 23, CreditCardType: UnionPay
ID: 24, CreditCardType: UnionPay
ID: 25, CreditCardType: Discover
ID: 26, CreditCardType: Discover
ID: 27, CreditCardType: Visa
ID: 28, CreditCardType: American Express
ID: 29, CreditCardType

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [5]:
#!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv  -P data/

# Load the CSV file into a DataFrame
filename = "data/mushrooms_categorized.csv"
df = pd.read_csv(filename)

# a. Explore and print the DataFrame
print(f"=> DataFrame : \n{df.head()}")

# b. Calculate the average value of each feature, separately for each class using groupby()
average = df.groupby('class').mean()
print(f"\n=> Average values for each class :\n{average}")

# c. Save the file in a JSON format
json_filename = "mushrooms_categorized_average.json"
average.to_json(json_filename, orient='index')


# Document content display
print("\nHere's the data contained in the document displayed with cat\n")
!cat mushrooms_categorized_average.json

=> DataFrame : 
   class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-col

4\. **Reading a database**

Get the database `sakila.db` from the lecture `06_dataio.ipynb`, and import the table `actors` as a Pandas dataframe. Using the dataframe, count how many actors have a first name that begins with `A`.

*Hint:* use the Series `.str` method to apply the Python string methods to the elements of a Series, see [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html).

In [6]:
#!wget https://gist.github.com/Piyush3dB/726bf7012785d6e0fd691c3655c92654/raw/2c17ccb2eb33b3396bfa96284c53f0718a4ea62c/sakila.db -P ./data/

import sqlite3 as sql # import the SQL module

# Connection to the sakila.db database
conn = sql.connect('data/sakila.db')
cur = conn.cursor()

# Query to select actors whose first name begins with 'A
query = "SELECT * FROM actor WHERE first_name LIKE 'A%'"
cur.execute(query)

# Creating a DataFrame from results
columns = [column[0] for column in cur.description]
df_actors = pd.DataFrame(cur.fetchall(), columns=columns)

# Closing the database connection
cur.close()
conn.close()

print(f"\nDataframe with actors' first names begin with 'A' : \n{df_actors}")

# Compter le nombre d'acteurs dont le prénom commence par 'A'
count_actors = df_actors.shape[0]
print(f"\nNumber of actors whose first name starts with 'A': {count_actors}")


Dataframe with actors' first names begin with 'A' : 
    actor_id first_name    last_name          last_update
0         29       ALEC        WAYNE  2019-02-16 18:17:33
1         34     AUDREY      OLIVIER  2019-02-16 18:17:33
2         49       ANNE       CRONYN  2019-02-16 18:17:33
3         65     ANGELA       HUDSON  2019-02-16 18:17:33
4         71       ADAM        GRANT  2019-02-16 18:17:33
5         76   ANGELINA      ASTAIRE  2019-02-16 18:17:33
6        125     ALBERT        NOLTE  2019-02-16 18:17:33
7        132       ADAM       HOPPER  2019-02-16 18:17:33
8        144     ANGELA  WITHERSPOON  2019-02-16 18:17:33
9        146     ALBERT    JOHANSSON  2019-02-16 18:17:33
10       165         AL      GARLAND  2019-02-16 18:17:33
11       173       ALAN     DREYFUSS  2019-02-16 18:17:33
12       190     AUDREY       BAILEY  2019-02-16 18:17:33

Number of actors whose first name starts with 'A': 13


5\. **Reading the credit card numbers**

Get the binary file named `credit_card.dat` from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [7]:
#!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat -P ./data/

credit_card_numbers = []

with open('data/credit_card.dat', 'rb') as file: # Open file in binary read mode
    for line in file: # Read each line of the file

        # Cut the binary data into 6-bit pieces, and ignoring the last 4 bits, which are padding
        numbers = [line[i:i+6] for i in range(0, len(line) - 4, 6)]
        # Convert each 6-bit pieces to its decimal representation, then to the corresponding character
        credit_card_number = ''.join([chr(int(num, 2)) for num in numbers])
        credit_card_numbers.append(credit_card_number)

with open('data/credit_card_numbers.txt', 'w') as output_file: # Write the credit card numbers to a new file
    for number in credit_card_numbers:
        output_file.write(number + '\n')

!cat data/credit_card_numbers.txt

7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

6\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [8]:
#from IPython.display import Image
#Image("images/data_format.png")

In [9]:
#!wget https://www.dropbox.com/s/ga9wi6b40cakgae/data_000637.txt -P data/

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, "pack" the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_dataio.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [10]:
# a.

import struct

df = pd.read_csv('data/data_000637.txt')

with open('data/output_binary_file.bin', 'wb') as binary_file:
    for i in range(len(df)): 
        row = df.iloc[i]
        head, fpga, tdc_chan, orb_cnt, bx, tdc_meas = row

        # Pack the values into a 64-bit word
        word = (
            ((head & 0x3) << 62) |
            ((fpga & 0xF) << 58) |
            ((tdc_chan & 0x1FF) << 49) |
            ((orb_cnt & 0xFFFFFFFF) << 17) |
            ((bx & 0xFFF) << 5) |
            (tdc_meas & 0x1F)
        )

        # Write the 64-bit word to the binary file
        binary_file.write(struct.pack('<q', word))

In [11]:
# b.

data = {}

with open('data/output_binary_file.bin', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        word = struct.unpack('<q', file_content[i : i + word_size])[0]  
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F

        entry = {
            'HEAD': head, 
            'FPGA': fpga, 
            'CHANNEL': tdc_chan, 
            'ORBIT_CNT': orb_cnt, 
            'BX_CNT': bx, 
            'TDC_MEAS': tdc_meas
        }
        data[word_counter] = entry
        
df = pd.DataFrame.from_dict(data, orient='index')
print(f"\nView the first 10 lines after unpacking : \n{df.head(10)}")


View the first 10 lines after unpacking : 
    HEAD  FPGA  CHANNEL   ORBIT_CNT  BX_CNT  TDC_MEAS
1      1     0      123  3869200167    2374        26
2      1     0      124  3869200167    2374        27
3      1     0       63  3869200167    2553        28
4      1     0       64  3869200167    2558        19
5      1     0       64  3869200167    2760        25
6      1     0       63  3869200167    2762         4
7      1     0       61  3869200167    2772        14
8      1     0      139  3869200167    2776         0
9      1     0       62  3869200167    2774        21
10     1     0       60  3869200167    2788         7


In [12]:
# c.

import os 

txt_file = os.path.getsize('./data/data_000637.txt')
bin_file = os.path.getsize('./data/output_binary_file.bin')

# Size of output_binary_file.bin : 10,5 MB
# Size of data_000637.txt : 33,2 MB

# The difference in size on disk between the text file (data_000637.txt) and the binary file (output_binary_file.bin) is approximately 22.7 MB. This indicates that the binary file is significantly smaller than the equivalent text file.

print(f"""
Size of output_binary_file.bin : {bin_file} bytes
Size of data_000637.txt : {txt_file} bytes

The difference in size on disk between the text file (data_000637.txt) and the binary file (output_binary_file.bin) is approximately {txt_file - bin_file} bytes. This indicates that the binary file is significantly smaller than the equivalent text file.
""")


Size of output_binary_file.bin : 10485760 bytes
Size of data_000637.txt : 33179236 bytes

The difference in size on disk between the text file (data_000637.txt) and the binary file (output_binary_file.bin) is approximately 22693476 bytes. This indicates that the binary file is significantly smaller than the equivalent text file.

