1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [ ]:
!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

In [111]:
import timeit
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import json
import sqlite3
import struct
import os

In [19]:
L = [1,2,3,4,5]
intFile = "data_int.txt"
with open(intFile, 'w') as outfile:
    for i in L:

        outfile.write(str(i) + " ") 



In [22]:

M = np.random.random(size=(5,5))
floatFile = "data_float.txt"

with open(floatFile, 'w') as outfile:
    for line in M:

        outfile.write(str(line) + "\n") 


In [33]:
df = pd.DataFrame(columns= ["a","b","c","d","e"])
print(len(df))
with open(floatFile, 'r') as outfile:
    for i in outfile:
        df.loc[len(df)] = i[1:-2].split()
print(M)
df

0
[[0.18839093 0.37002377 0.025958   0.24229688 0.85228796]
 [0.80905194 0.44580816 0.18164228 0.83977596 0.50043373]
 [0.64976814 0.76582669 0.36069722 0.64066731 0.86135676]
 [0.68857039 0.8051368  0.54676964 0.04500472 0.38148313]
 [0.39709792 0.57948861 0.93218826 0.47546085 0.03900744]]


a           b           c           d           e
0  0.18839093  0.37002377    0.025958  0.24229688  0.85228796
1  0.80905194  0.44580816  0.18164228  0.83977596  0.50043373
2  0.64976814  0.76582669  0.36069722  0.64066731  0.86135676
3  0.68857039   0.8051368  0.54676964  0.04500472  0.38148313
4  0.39709792  0.57948861  0.93218826  0.47546085  0.03900744

2\. **JSON files**

Load the file `user_data.json`, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [51]:

data = json.load(open('user_data.json'))
df = pd.DataFrame(data)
print(df)
df2 = df[df["CreditCardType"] == "American Express"]

      ID             JobTitle                    EmailAddress  \
0      1      Project Manager    Remy_Crawford1065@typill.biz   
1      2  Investment  Advisor    Clint_Thorpe5003@bulaffy.com   
2      3                 Cook   Russel_Hooper9403@bulaffy.com   
3      4      Business Broker   Benjamin_Rowan6280@gembat.biz   
4      5         Loan Officer       Matt_Lloyd3241@guentu.biz   
..   ...                  ...                             ...   
195  196         Loan Officer        Wade_Khan6086@twipet.com   
196  197                 Cook         Ally_Rose8531@twace.org   
197  198     Machine Operator      Harvey_Moore7505@extex.org   
198  199  Investment  Advisor      Ryan_Kennedy5565@corti.com   
199  200          Stockbroker  Michaela_Murphy8359@ovock.tech   

    FirstNameLastName           CreditCard    CreditCardType  
0       Remy Crawford  6205-7258-7671-0612       Capital One  
1        Clint Thorpe  7083-8766-0251-2345  American Express  
2       Russel Hooper  6378-44

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [48]:
df = pd.read_csv("mushrooms_categorized.csv")
jsonFile = "ex3.json"


dataMeans = df.groupby(["class"]).mean()
dataMeans.to_json(jsonFile, orient='columns')
dataMeans


cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

4\. **Reading a database**

Get the database `sakila.db` from the lecture `06_dataio.ipynb`, and import the table `actors` as a Pandas dataframe. Using the dataframe, count how many actors have a first name that begins with `A`.

*Hint:* use the Series `.str` method to apply the Python string methods to the elements of a Series, see [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html).

In [62]:
conn = sqlite3.connect("sakila.db")
df =  pd.read_sql_query("SELECT * FROM actor;", conn)
countFirstNameA = df['first_name'].str.startswith('A').sum()
countFirstNameA


13

5\. **Reading the credit card numbers**

Get the binary file named `credit_card.dat` from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [104]:
with open("credit_card.dat", 'rb') as binary_file:
    L = []
    
    for line in binary_file:
        credit_card_num = ""
        j = 0
        for i in range(19):
            if len(line) >= j + 6:
                binary_num = line[j:j+6]
                int_num = int(binary_num, 2)
                credit_card_num += chr(int_num)
                j += 6
            else:
                break
        L.append(credit_card_num)

print(L)


['7648 5673 3775 2271', '3257 8247 3354 2266', '2722 0001 4011 6652', '0661 3063 3742 3150', '0432 1608 1462 4742', '5827 2027 8785 7303', '5774 8528 2087 1117', '8140 1210 6352 2845', '5764 1133 7301 7100', '6456 1737 4126 6726', '1228 8631 7382 0000', '7051 0160 5374 3166', '0618 3587 1630 6376', '1545 5454 7444 5636', '6735 3116 3202 6834', '7287 5011 1547 8413', '7033 2607 3328 4200', '2568 5244 1874 5024', '1684 2253 7570 7118', '0672 2576 0575 6631', '6332 8353 8787 1340', '1813 3361 1175 4211', '2477 6450 8840 2368', '5512 3505 2563 1326', '3083 7882 0621 0025', '4521 5148 8045 0334', '7563 3654 8713 5787', '8324 2664 0476 5561', '0565 2504 7168 3510', '5107 5507 1767 0738', '2462 1821 2448 1443', '2788 0638 6861 6554', '5851 5873 5474 0547', '0670 1004 4013 2655', '5874 5506 3048 0806', '2805 5401 8462 1260', '5083 8406 6310 1862', '1076 1445 3013 2266', '8440 4804 4844 5277', '4758 6141 0686 1387', '7586 0675 0315 2568', '2544 1258 7432 5165', '3474 5023 4434 5626', '1410 0270

6\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, "pack" the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_dataio.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [105]:
data637 = pd.read_csv('data_000637.txt', nrows = 10)
data637

HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
0     1     0          123  3869200167        2374        26
1     1     0          124  3869200167        2374        27
2     1     0           63  3869200167        2553        28
3     1     0           64  3869200167        2558        19
4     1     0           64  3869200167        2760        25
5     1     0           63  3869200167        2762         4
6     1     0           61  3869200167        2772        14
7     1     0          139  3869200167        2776         0
8     1     0           62  3869200167        2774        21
9     1     0           60  3869200167        2788         7

In [108]:
out_file_name = "binary_file.dat"

with open(out_file_name, 'wb') as binary_file:
  for line in data637.values : 
    word = (line[5] << 0 ) 
    word += (line[4] << 5 ) 
    word += (line[3] << 17) 
    word += (line[2] << 49) 
    word += (line[1] << 58)
    word += (line[0] << 62)

    binary_file.write( struct.pack('<q', word) )

In [109]:
#------------------------------------- Question b ---------------------------------------
data = {}
columns = ['HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS']
df = pd.DataFrame({}, columns=columns)

with open('binary_file.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        df = df.append(entry, ignore_index=True)

df

C:\Users\MOUHEB\AppData\Local\Temp\ipykernel_8168\1369913096.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
C:\Users\MOUHEB\AppData\Local\Temp\ipykernel_8168\1369913096.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
C:\Users\MOUHEB\AppData\Local\Temp\ipykernel_8168\1369913096.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
C:\Users\MOUHEB\AppData\Local\Temp\ipykernel_8168\1369913096.py:21: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(entry, ignore_index=True)
C:\Users\MOUHEB\AppData\

HEAD FPGA CHANNEL   ORBIT_CNT BX_CNT TDC_MEAS
0    1    0     123  3869200167   2374       26
1    1    0     124  3869200167   2374       27
2    1    0      63  3869200167   2553       28
3    1    0      64  3869200167   2558       19
4    1    0      64  3869200167   2760       25
5    1    0      63  3869200167   2762        4
6    1    0      61  3869200167   2772       14
7    1    0     139  3869200167   2776        0
8    1    0      62  3869200167   2774       21
9    1    0      60  3869200167   2788        7

In [112]:
data637.to_csv('text_file.txt', sep=' ', index=False)
file_size = 0
with open('text_file.txt', 'r') as file:
  for i in file:
    file_size += len(i)
print('The size of the binary file calculated by Os module: ', os.stat('text_file.txt').st_size, 'bytes')
print('The size of the binary file calculated manually : ',file_size, 'bytes')

The size of the binary file calculated by Os module:  323 bytes
The size of the binary file calculated manually :  312 bytes


In [113]:
print('The size of the binary file calculated by Os module: ', os.stat('binary_file.dat').st_size, 'bytes')
print('The size of the binary file calculated manually : ', word_counter * word_size, 'bytes')

The size of the binary file calculated by Os module:  80 bytes
The size of the binary file calculated manually :  80 bytes
