1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [21]:
import pandas as pd
import csv
import numpy as np
import json

In [20]:
list_int=[1,2,3,4]
f = open('data/data_int.txt', 'w')
f.write(str(list_int))
f.close()
!cat data/data_int.txt

import numpy as np
matrix = np.arange(1.0,6.0,0.2).reshape(5,5)
with open('data/data_float.txt','w') as f:
    f.write(str(matrix))

print()
!cat data/data_float.txt

with open('data/data_float.txt','r') as file:
    lines = file.readlines()
with open('data/data_float.csv','w', newline='') as output:
    csv_writer = csv.writer(output)
    for line in lines:
        csv_writer.writerow([line.strip()])

!cat data/data_float.csv

    

[1, 2, 3, 4]
[[1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]
 [5.  5.2 5.4 5.6 5.8]][[1.  1.2 1.4 1.6 1.8]
[2.  2.2 2.4 2.6 2.8]
[3.  3.2 3.4 3.6 3.8]
[4.  4.2 4.4 4.6 4.8]
[5.  5.2 5.4 5.6 5.8]]


2\. **JSON files**

Load the file `user_data.json`, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [41]:
data = json.load(open('data/user_data.json'))

data = [person for person in data if person["CreditCardType"] == 'American Express']
print(data)
with open('data/output_csv.csv', 'w', newline='') as output_csv:
    csv_writer = csv.writer(output_csv)

    # Write the header to the CSV file based on the keys of the first dictionary
    csv_writer.writerow(data[0].keys())

    # Write each row to the CSV file
    for person in data:
        csv_writer.writerow(person.values())

[{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}, {'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}, {'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}, {'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}, {'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCard

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [46]:
file_name= "data/mushrooms_categorized.csv"
data = pd.read_csv(file_name)
# Explore and print the DataFrame
print("First few rows:")
print(data.head())

print("\nDataFrame information:")
print(data.info())

print("\nSummary statistics:")
print(data.describe())

print("\nColumn names:")
print(data.columns)

print("\All DataFrame:")
print(data)


First few rows:
   class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-col

4\. **Reading a database**

Get the database `sakila.db` from the lecture `06_dataio.ipynb`, and import the table `actors` as a Pandas dataframe. Using the dataframe, count how many actors have a first name that begins with `A`.

*Hint:* use the Series `.str` method to apply the Python string methods to the elements of a Series, see [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html).

5\. **Reading the credit card numbers**

Get the binary file named `credit_card.dat` from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

6\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, "pack" the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_dataio.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?