In [3]:
import pandas as pd
import numpy as np
import json
import struct
import os

In [4]:
!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
!wget https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json
!wget https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv
!wget https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

--2023-12-08 10:18:22--  https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
Resolving www.dropbox.com (www.dropbox.com)... 162.125.13.18, 2620:100:6057:18::a27d:d12
Connecting to www.dropbox.com (www.dropbox.com)|162.125.13.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/xvjzaxzz3ysphme/data_000637.txt [following]
--2023-12-08 10:18:22--  https://www.dropbox.com/s/raw/xvjzaxzz3ysphme/data_000637.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc34a9c59c1391839d1d58ca2ccb.dl.dropboxusercontent.com/cd/0/inline/CJBnOV9-SLB6yqBQAnBpukZq7fXAxE3ZjtEoNGv1qx-MtmmSRI56jYD-dpBkTeyzxusf1G6fQESQI0XN9XftZ_hQezvukWPsujHYvCYSik7YBGCPv51GsAoBDJzQGWQaSCI/file# [following]
--2023-12-08 10:18:23--  https://uc34a9c59c1391839d1d58ca2ccb.dl.dropboxusercontent.com/cd/0/inline/CJBnOV9-SLB6yqBQAnBpukZq7fXAxE3ZjtEoNGv1qx-MtmmSRI56jYD-dpBkTeyzxusf1G6fQESQI0XN9XftZ_hQezvukWPsujHYvCYSik7YBGCP

1\. **Text files**



In [6]:
# create a list of integrer numbers and then save it to a text file named data_int.txt. Run the cat command to print the content of the file.

List_Integers = range(1,10)

out_file_name = "data_int.txt"

with open(out_file_name, 'w') as outfile:
  for line in List_Integers:
    outfile.write(str(line) + '\n')

!cat data_int.txt
Matrix_Float = np.random.random(size=(5,5))
file_name = "data_float.txt"
with open(file_name, 'w') as outfile:
  for line in Matrix_Float:
    outfile.write(str(line) + '\n')

!cat data_float.txt

1
2
3
4
5
6
7
8
9
[0.630966   0.95661242 0.2283087  0.7570467  0.66407719]
[0.60005557 0.81218309 0.16968555 0.90718653 0.37426303]
[0.07699305 0.23461548 0.97960759 0.258476   0.94666969]
[0.81974493 0.11052044 0.01943047 0.71969436 0.94045927]
[0.80116585 0.14144251 0.23675764 0.43465031 0.95485428]


In [7]:
file_name = "data_float.txt"
df = pd.DataFrame(columns = ['0' , '1', '2' , '3','4'])

with open(file_name, 'r') as outfile:
  for line in outfile:
    df.loc[len(df)] = line[1:-2].split()


In [8]:
df

0           1           2           3           4
0    0.630966  0.95661242   0.2283087   0.7570467  0.66407719
1  0.60005557  0.81218309  0.16968555  0.90718653  0.37426303
2  0.07699305  0.23461548  0.97960759    0.258476  0.94666969
3  0.81974493  0.11052044  0.01943047  0.71969436  0.94045927
4  0.80116585  0.14144251  0.23675764  0.43465031  0.95485428

2\. **JSON files**


In [9]:
data = json.load(open('user_data.json'))
df = pd.DataFrame(columns = ['ID' , 'JobTitle', 'EmailAddress' , 'FirstNameLastName','CreditCard','CreditCardType'])
for line in data :
  df.loc[len(df)] = line.values()
df = df.set_index('ID')
filter = df[df["CreditCardType"] == 'American Express']
filter.to_csv('user_data.csv')

In [10]:
filter

JobTitle                       EmailAddress  \
ID                                                              
2      Investment  Advisor       Clint_Thorpe5003@bulaffy.com   
12          Retail Trainee   Phillip_Carpenter9505@famism.biz   
28         Project Manager        Russel_Graves1378@extex.org   
39             Stockbroker       Leanne_Newton1268@typill.biz   
57          Budget Analyst          Tony_Giles1960@iatim.tech   
62            CNC Operator        Owen_Allcott5125@bauros.biz   
68         Project Manager           Liam_Lynn3280@kideod.biz   
74                 Dentist      Regina_Woodcock5820@yahoo.com   
81           HR Specialist       Carter_Wallace9614@atink.com   
92     Staffing Consultant           Maia_Stark2797@jiman.org   
97             Stockbroker          Ciara_Lomax982@bauros.biz   
116    Staffing Consultant      Isabel_Ellwood1475@fuliss.net   
148           CNC Operator  Abdul_Townend2202@infotech44.tech   
150             Fabricator        Caleb_Poulton1735@atink.com   
151     Restaurant Manager         Ronald_Lewis6777@deavo.com   
154                Bellman        Faith_Seymour3829@twace.org   
169        Assistant Buyer      Anthony_Hancock9083@qater.org   
176  Healthcare Specialist    Isabella_Willson5478@nanoff.biz   
182             Pharmacist     Stephanie_Darcy3298@bauros.biz   
199    Investment  Advisor         Ryan_Kennedy5565@corti.com   

     FirstNameLastName           CreditCard    CreditCardType  
ID                                                             
2         Clint Thorpe  7083-8766-0251-2345  American Express  
12   Phillip Carpenter  3657-0088-0820-5247  American Express  
28       Russel Graves  6718-4818-8011-6024  American Express  
39       Leanne Newton  5438-0816-4166-4847  American Express  
57          Tony Giles  8130-3425-7573-7745  American Express  
62        Owen Allcott  4156-0107-7210-2630  American Express  
68           Liam Lynn  7152-3247-6053-2233  American Express  
74     Regina Woodcock  0208-1753-3870-8002  American Express  
81      Carter Wallace  4256-7201-6717-4322  American Express  
92          Maia Stark  3851-1403-1734-6321  American Express  
97         Ciara Lomax  3702-3440-2472-5424  American Express  
116     Isabel Ellwood  3738-0882-0066-6683  American Express  
148      Abdul Townend  4224-1226-3557-3448  American Express  
150      Caleb Poulton  8203-6875-5225-0341  American Express  
151       Ronald Lewis  7212-0155-5014-8471  American Express  
154      Faith Seymour  4170-5186-6887-6558  American Express  
169    Anthony Hancock  0832-3357-6010-6550  American Express  
176   Isabella Willson  5177-4868-4623-0384  American Express  
182    Stephanie Darcy  0264-4020-5106-5576  American Express  
199       Ryan Kennedy  3166-6287-6242-7207  American Express

3\. **CSV files with Pandas**

In [15]:
data  = pd.read_csv('mushrooms_categorized.csv')
data

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [17]:
dataGroupBy = data.groupby('class').mean()
print("Average values of each feature, separately for each class = ", dataGroupBy)
dataGroupBy.to_json('mushrooms_categorized.json')


Average values of each feature, separately for each class =         cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                   

In [18]:
dataGroupBy

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
class                                                                           
0       3.266160     1.615970   4.581749  0.653992  4.334601         0.954373   
1       3.436159     2.055158   4.421859  0.159346  3.940756         0.995403   

       gill-spacing  gill-size  gill-color  stalk-shape  ...  \
class                                                    ...   
0          0.285171   0.068441    6.622624     0.615970  ...   
1          0.028601   0.567926    2.863636     0.514811  ...   

       stalk-surface-below-ring  stalk-color-above-ring  \
class                                                     
0                      1.798479                6.098859   
1                      1.394280                5.512768   

       stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
class                                                                          
0                    6.064639        0.0    1.931559     1.125475   3.007605   
1                    5.504597        0.0    2.002043     1.009193   1.522983   

       spore-print-color  population   habitat  
class                                           
0               3.201521    3.283270  1.148289  
1               4.021450    4.031665  1.895812  

[2 rows x 22 columns]

4\. **Reading a database**


In [28]:
!wget https://gist.github.com/Piyush3dB/726bf7012785d6e0fd691c3655c92654/raw/2c17ccb2eb33b3396bfa96284c53f0718a4ea62c/sakila.db -P ./data/



--2023-12-08 10:34:58--  https://gist.github.com/Piyush3dB/726bf7012785d6e0fd691c3655c92654/raw/2c17ccb2eb33b3396bfa96284c53f0718a4ea62c/sakila.db
Resolving gist.github.com (gist.github.com)... 140.82.112.3
Connecting to gist.github.com (gist.github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gist.githubusercontent.com/Piyush3dB/726bf7012785d6e0fd691c3655c92654/raw/2c17ccb2eb33b3396bfa96284c53f0718a4ea62c/sakila.db [following]
--2023-12-08 10:34:58--  https://gist.githubusercontent.com/Piyush3dB/726bf7012785d6e0fd691c3655c92654/raw/2c17ccb2eb33b3396bfa96284c53f0718a4ea62c/sakila.db
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5828608 (5.6M) [application/octet-stream]
Saving to: ‘

In [31]:
import sqlite3 as sql
conn = sql.connect('sakila.db')
cur = conn.cursor()
query = "SELECT * FROM actors"
df4 = pd.read_sql_query(query, conn) # loading the result to a dataframe.
conn.close() #close the database connection
a_actors = df4[df4['first_name'].str.startswith('A')] # returns a dataframe from df4 that cntains only the actors that their names starts with a.
nb_a_actors = len(a_actors)
print("The number of actors with that their first name starts with a:", nb_a_actors)


DatabaseError: ignored

5\. Reading the credit card numbers

In [32]:
!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ./data/

--2023-12-08 10:40:55--  https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt
Resolving www.dropbox.com (www.dropbox.com)... 162.125.13.18, 2620:100:6057:18::a27d:d12
Connecting to www.dropbox.com (www.dropbox.com)|162.125.13.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/xvjzaxzz3ysphme/data_000637.txt [following]
--2023-12-08 10:40:55--  https://www.dropbox.com/s/raw/xvjzaxzz3ysphme/data_000637.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucf936c13fa3ebcac585913e62fe.dl.dropboxusercontent.com/cd/0/inline/CJBh6-WWWGIt1TBE0HpinT5rUw0VSDfafmBljtjnj_Dczy9o6im_InSeaaM0i-ZojsZJAMeCsVGxvNfby4dmKSMKsm1PipP0KVcIdq7_uBX6UTJWuJhFZRBxaRw5buJ_f3M/file# [following]
--2023-12-08 10:40:55--  https://ucf936c13fa3ebcac585913e62fe.dl.dropboxusercontent.com/cd/0/inline/CJBh6-WWWGIt1TBE0HpinT5rUw0VSDfafmBljtjnj_Dczy9o6im_InSeaaM0i-ZojsZJAMeCsVGxvNfby4dmKSMKsm1PipP0KVcIdq7_uBX6UTJW

In [36]:
import struct
file= 'data_000637.txt'
data1=[]
df = pd.read_csv(file, sep=",", nrows=10)
print(df)
with open(file, 'wb') as binary_file:
    for _, row in df.iterrows(): #iterating the dataframe using iterrows predefined function.
        pack_val = struct.pack('<q',int(row['HEAD']) << 48 | int(row['FPGA']) << 32 | int(row['TDC_CHANNEL']) << 16 | int(row['ORBIT_CNT']))
        binary_file.write(pack_val)
        unpacked_values = struct.unpack('<q', pack_val)
        data1.append(unpacked_values[0])

print("done!")
df_txt = pd.read_csv(file, sep=",", encoding='utf-8')


if list(df_txt['HEAD']) ==data1:
    print("the data consistency is verified!")
else:
    print("error!")
import os

text_size = os.path.getsize(file)
binary_size = os.path.getsize(file)
print(f"Size on disk for text file: ", text_size)
print(f"Size on disk for binary file: ", binary_size)

UnicodeDecodeError: ignored