1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [49]:
import numpy as np
import random

#creating a list of integer numbers
integers = [random.randint(1, 50) for i in range(50)]

with open('data_int.txt', "w") as f:
    f.write(str(integers))

!type .\data_int.txt

five_by_five = np.array([
    [random.randint(1, 50) for j in range(5)] for i in range(5)
],dtype=float)

with open("data_float.txt", "w") as f:
    f.write(str(five_by_five))
    
!type .\data_float.txt

#processing the txt content into csv
with open("data_float.txt", "r") as f:
    matrix = f.read()
    text = matrix.replace("[","").replace("]", "").replace(". ", ".,").replace(" ", "")

#writing the csv content to disk
with open("data_float.txt", "w") as f:
    f.write(text)


[33, 30, 18, 13, 8, 22, 11, 47, 30, 42, 17, 46, 12, 1, 48, 22, 19, 37, 44, 49, 13, 12, 40, 41, 26, 28, 33, 21, 6, 26, 43, 7, 12, 9, 31, 21, 16, 1, 17, 25, 16, 29, 49, 18, 22, 20, 38, 47, 37, 1]
[[17. 42. 24. 45. 16.]
 [ 4. 43.  8. 30. 20.]
 [11. 26. 44. 33. 46.]
 [50. 20. 45.  8. 41.]
 [19. 24. 40. 15. 15.]]


2\. **JSON files**

Load the file `user_data.json`, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [54]:
import pandas as pd

df = pd.read_json('./user_data.json')

df[df['CreditCardType'] == 'American Express']

df.to_csv('user_data.csv', index=False)

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

4\. **Reading a database**

Get the database `sakila.db` from the lecture `06_dataio.ipynb`, and import the table `actors` as a Pandas dataframe. Using the dataframe, count how many actors have a first name that begins with `A`.

*Hint:* use the Series `.str` method to apply the Python string methods to the elements of a Series, see [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html).

5\. **Reading the credit card numbers**

Get the binary file named `credit_card.dat` from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

6\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, "pack" the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_dataio.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?