1\. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integrer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [2]:
l=[1,2,3,4]
f=open('data/data_int.txt', 'w')
f.write(str(l))
f.close()
#!cat data_int.txt
!type data\data_int.txt
import numpy.random as npr
m=npr.rand(5, 5)
g=open('data/data_float.txt','w')
g.write(str(m))
g.close()
#!cat data_int.txt
!type data\data_float.txt #equivalente di cat


[1, 2, 3, 4]
[[0.94333551 0.35266247 0.64604252 0.40206234 0.65691699]
 [0.17963127 0.40246172 0.01233075 0.51604961 0.54024938]
 [0.26897492 0.58530442 0.76454524 0.2310344  0.50324465]
 [0.53197627 0.27998464 0.36723576 0.71255295 0.20372136]
 [0.93397753 0.14773583 0.06956368 0.00848783 0.98506001]]



data\data_float.txt


Impossibile trovare il file specificato.
Errore occorso durante l'elaborazione: #equivalente.
Impossibile trovare il file specificato.
Errore occorso durante l'elaborazione: di.
Impossibile trovare il file specificato.
Errore occorso durante l'elaborazione: cat.


In [3]:
import csv
import pandas as pd

read_file = pd.read_csv ('data\data_float.txt')
read_file.to_csv ('data\data_float.csv', index=None)

2\. **JSON files**

Load the file `user_data.json`, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [4]:
import json # import the JSON module
data = json.load(open('data/user_data.json'))
f=open('data/use_data_AE.txt', 'w')
#print(data)
for i in range(len(data)):
    if data[i]['CreditCardType']=='American Express':
        print(data[i])
        f.write(str(data[i]))
f.close()        


{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}
{'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}
{'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}
{'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}
{'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCardType'

3\. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [5]:
import pandas as pd

df= pd.read_csv ('data\mushrooms_categorized.csv')
print(df)
c=df.groupby('class').mean()
#print(c)
c.to_json('data/mushrooms_categorized_n.json', orient="records")


      class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                 

4\. **Reading a database**

Get the database `sakila.db` from the lecture `06_dataio.ipynb`, and import the table `actors` as a Pandas dataframe. Using the dataframe, count how many actors have a first name that begins with `A`.

*Hint:* use the Series `.str` method to apply the Python string methods to the elements of a Series, see [documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html).

In [6]:
import sqlite3 as sql
import pandas as pd
conn = sql.connect('data\sakila.db')
cur = conn.cursor()
print(cur)
query = "SELECT * FROM actor;"
results = cur.execute(query).fetchall()
df = pd.DataFrame(results)
print(df)
# Close the database connection

# Count the actors with a first name that begins with 'A'
countA = df[df[1].str.startswith('A')].shape[0]
print(f"Number of actors with a first name starting with 'A': ", countA)
conn.close()



       0         1             2                    3
0      1  PENELOPE       GUINESS  2019-02-16 18:17:33
1      2      NICK      WAHLBERG  2019-02-16 18:17:33
2      3        ED         CHASE  2019-02-16 18:17:33
3      4  JENNIFER         DAVIS  2019-02-16 18:17:33
4      5    JOHNNY  LOLLOBRIGIDA  2019-02-16 18:17:33
..   ...       ...           ...                  ...
195  196      BELA        WALKEN  2019-02-16 18:17:33
196  197     REESE          WEST  2019-02-16 18:17:33
197  198      MARY        KEITEL  2019-02-16 18:17:33
198  199     JULIA       FAWCETT  2019-02-16 18:17:33
199  200     THORA        TEMPLE  2019-02-16 18:17:33

[200 rows x 4 columns]
Number of actors with a first name starting with 'A':  13


5\. **Reading the credit card numbers**

Get the binary file named `credit_card.dat` from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [7]:
import struct, time
import os
#hexdump("data/credit_card.dat")io
f="data/credit_card.dat"
script_dir = directory_path = os.getcwd()
abs_file_path = os.path.join(script_dir, f)
print(abs_file_path)
creditcards = []
with open("data/credit_card.dat", "rb") as file:
    line_data = file.readline()
    print(binary_data)
    while line_data:
        if len(line_data) < 118:
            break
        creditcard = ""
        for i in range(19):
            substring = line_data[i * 6 + 2:i * 6 + 6]
            if (i+1) % 5 == 0:
                creditcard = creditcard + ' '
            else:
                digit = int(substring, base=2)
            creditcard = creditcard + str(digit)
        creditcards.append(creditcard)
        line_data = file.readline()
#for i in binary_data:
#for i in range(0, len(binary_data), 6):
    #word = struct.unpack('<q', binary_data[i : i + 6]+b'\x00\x00') # get an 8-byte word
    #print(word)
print(creditcards)

C:\Users\laura\ScientificComputingWithPython2023\data/credit_card.dat


NameError: name 'binary_data' is not defined

6\. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

In [ ]:
from IPython.display import Image
Image("images/data_format.png")


*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, "pack" the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_dataio.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [ ]:
import struct
import pandas as pd
datatxt = pd.read_csv('data/data_000637.txt', nrows=10)
#print(datatxt)
#newfilerelativepath = "data/data_000637_new.dat"
binary_file = open("data/data_000637_new.dat", 'wb')
for i in range(len(datatxt)):
    word = ((datatxt.iloc[i, 0] & 0x3) << 62 |
    (datatxt.iloc[i, 1] & 0xF) << 58 |
    (datatxt.iloc[i, 2] & 0x1FF) << 49 |
    (datatxt.iloc[i, 3] & 0xFFFFFFFF) << 17 |
    (datatxt.iloc[i, 4] & 0xFFF) << 5 |
    (datatxt.iloc[i, 5] & 0x1F))
    binary_file.write( struct.pack('<q', word) )
binary_file.close()
data = {}
columns = ['HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS']
df = pd.DataFrame({}, columns=columns)
with open("data/data_000637_new.dat", 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        if word_counter > 10: break
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        #if i == 0: print ('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format('HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'))
        #print('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        #df = df.append(entry, ignore_index=True)
        data[word_counter] = entry
        
df = pd.DataFrame(data).T
df
'''
On average, each row in the text file consumes an additional 18 bytes compared to its counterpart in the
binary packed dat file.This disparity arises from the encoding overhead (ASCII or Unicode) and the presence
of additional characters, such as newline characters, in the text file. In contrast, the binary packed dat 
file is more space-efficient, resulting in a smaller size per row (8 bytes).'''