In [1]:
#q1
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)

total_mean =np.mean(m)

rows_mean=np.mean(m, axis=1)
cols_mean=np.mean(m, axis=0)


print(f'The total mean is :  {total_mean}')
print(f'The rows mean is :  {rows_mean}')
print(f'The column mean is :  {cols_mean}')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The total mean is :  5.5
The rows mean is :  [1.5 5.5 9.5]
The column mean is :  [4. 5. 6. 7.]


In [2]:
#q2
import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

outer_=np.outer(u,v)

print(outer_)

#using list comprehension
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
outer=[[i*j for j in v] for i in u]

print (outer)

##broadcasting
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
import numpy as np
outer__=u*v
print(outer__)


[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[[2, 4, 6, 8], [6, 12, 18, 24], [10, 20, 30, 40], [14, 28, 42, 56]]
[ 2 12 30 56]


In [3]:
#q3
import numpy as np
# initializing 10x6 matrix of random numbers between 0 and 3
mat = np.random.uniform(low=0.0, high=3.0, size=(10, 6))
# Create a mask for values less than 0.3
mask = mat < 0.3
# Apply the mask to set values less than 0.3 to zero
mat[mask] = 0
print(mat)


[[2.84953927 1.68957786 0.         0.68823971 1.27384346 0.        ]
 [2.48653506 0.89833565 2.80652206 1.14647034 1.57535668 2.61716613]
 [0.7105684  0.         2.20299261 0.         1.06731209 2.7665391 ]
 [1.90176318 1.10429259 1.50149259 1.00596453 0.59697155 1.82369247]
 [1.1247933  0.         0.96948308 0.96714997 1.82834392 2.27939749]
 [2.13780941 2.19285974 2.70565077 0.61522953 2.5623366  0.36138893]
 [0.68013789 0.44599904 1.20715594 1.59634216 0.85315616 2.31614584]
 [2.90806219 1.34193394 1.32123177 2.08015294 2.18763493 1.10383005]
 [0.54318101 2.38330364 0.37493988 1.95358062 0.49411442 2.54011605]
 [2.43078934 2.98978484 0.33974895 1.68300277 2.72515191 2.69072402]]


In [4]:
###q4

import numpy as np
arr = np.linspace(0, 2 * np.pi, 100)
Tenth = arr[::10]
reversed_arr = arr[::-1]
sin_values = np.sin(arr)
cos_values = np.cos(arr)
# Extract elements where the absolute difference between sin and cos is < 0.1
close_values_indices = np.where(np.abs(sin_values - cos_values) < 0.1)
close_values = arr[close_values_indices]

print(sin_values)


[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [5]:
#q5
import numpy as np

# Create 10x10 multiplication table
matrix = np.arange(1, 11)[:, None] * np.arange(1, 11)
# Find the trace of the matrix
tr = np.trace(matrix)
#Anti-diagonal matrix
anti_diagonal = np.diagonal(np.flip(matrix, axis=1))
#Diagonal offset by 1 upwards
offset_diagonal = np.diagonal(matrix, offset=1)
print("Matrix:")
print(matrix)
print("\nTrace of the matrix:", tr)
print("\nAnti-diagonal matrix:", anti_diagonal)
print("\nDiagonal offset by 1 upwards:", offset_diagonal)


Matrix:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

Trace of the matrix: 385

Anti-diagonal matrix: [10 18 24 28 30 30 28 24 18 10]

Diagonal offset by 1 upwards: [ 2  6 12 20 30 42 56 72 90]


In [6]:
#q6
import numpy as np
# Positions of cities along Route 66 in miles
location_miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
# Calculate the differences to get the distances between cities
distances_miles = np.abs(location_miles[:, np.newaxis] - location_miles)
# 1 mile = 1.60934 kilometers
conversion_factor = 1.60934  
# Convert distances from miles to kilometers using broadcasting
distances_km = distances_miles * conversion_factor

# Display the 2D grid of distances in kilometers
print("2D grid of distances in kilometers:")
print(distances_km)


2D grid of distances in kilometers:
[[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47424  865.82492  696.84422    0.       217.2609   706.50026
  1189.30226 1300.34672 1894.19318 2755.19008]
 [1401.73514 1083.08582  914.10512  217.2609     0.       489.23936
   972.04136 1083.08582 1676.93228 2537.92918]
 [1890.9745  1572.32518 1403.34448  706.50026  489.23936    0.
   482.802    593.84646 1187.69292 2048.68982]
 [2373.7765  2055.12718 1886.14648 1189.30226  972.04136  482.802
     0.       111.04446  704.89092 1565.88782]
 [2484.82096 2166.17164 1997.19094 1300.34672 1083.08582  593.84646
   111.04446    0.       593.84646 1454.84336]
 [3078.66742 2760.0181  2591.0374  1894.19318 1676.9

In [6]:
##q7
import numpy as np
import timeit

def sieve_of_eratosthenes_basic(N):
    # Create a boolean mask of shape (N,)
    mask = np.ones(N, dtype=bool)
    mask[:2] = False

    for i in range(2, int(np.sqrt(N)) + 1):
        if mask[i]:
            mask[i * i:N:i] = False  

    # Generate array of ordered prime numbers
    primes = np.nonzero(mask)[0]
    return primes

# Define N value
N = 100000

# Measure the time taken to compute primes using the basic sieve
time_basic = timeit.timeit(lambda: sieve_of_eratosthenes_basic(N), number=1)

print(f"Prime numbers using basic sieve for N = {N}:")
print(sieve_of_eratosthenes_basic(N))
print(f"\nTime taken for basic sieve with N = {N}: {time_basic} seconds")

##for large value of N the execution time increases

Prime numbers using basic sieve for N = 100000:
[    2     3     5 ... 99971 99989 99991]

Time taken for basic sieve with N = 100000: 0.002455378999002278 seconds


In [9]:
#q8
import numpy as np
import matplotlib.pyplot as plt
# Number of walkers and steps
walkers = 1000
steps = 200
# Generate a 2D array representing the random walk for each walker
random_walks = np.random.choice([-1, 1], size=(walkers, steps))
# Calculate the walking distances for each walker
distances = np.cumsum(random_walks, axis=1)
squared_distances = distances ** 2
# Compute the mean of squared distances at each step
mean_distances = np.mean(squared_distances, axis=0)
# Calculating the square root of mean squared distances to get the typical distance
typical_distances = np.sqrt(mean_distances)
print(mean_distances)
print(typical_distances)


[  1.      2.028   2.848   3.86    4.936   5.744   6.344   7.36    8.472
   9.668  10.2    11.412  12.36   13.288  14.472  15.2    16.488  17.608
  18.672  20.16   21.248  22.172  23.224  23.964  25.328  26.916  27.816
  29.368  30.144  31.992  32.792  33.244  34.568  35.28   35.56   36.748
  38.376  40.052  41.248  41.612  43.672  45.46   46.52   47.852  49.344
  50.736  52.056  53.564  53.752  54.584  55.648  56.328  57.68   59.208
  60.536  61.188  62.464  62.812  63.88   64.376  65.304  66.084  66.24
  67.492  68.712  70.776  71.672  72.632  74.304  74.956  75.72   76.712
  78.064  79.348  80.472  81.132  82.368  82.892  82.888  83.804  84.888
  85.252  86.296  87.66   87.88   88.744  88.768  88.82   90.408  90.876
  92.288  93.96   94.784  96.076  96.68   96.916  98.976  99.724 100.152
 100.616 101.416 102.256 103.016 104.252 105.088 105.956 105.928 105.868
 107.64  109.56  109.656 111.576 112.544 113.148 114.136 114.616 116.096
 116.488 116.168 117.52  118.072 118.956 119.624 119