In [2]:
import pandas as pd
import numpy as np
import struct
import pandas as pd
import random
import json
import csv
import urllib.request
import sqlite3 as sql

1. **Text files**

Perform the following operations on plain `txt` files:

+ create a list of integer numbers and then save it to a text file named `data_int.txt`. Run the `cat` command to print the content of the file.
+ create a matrix of 5x5 floats and then save it to a text file named `data_float.txt`. Use the `cat` command to print the content of the file.
+ load the `txt` file of the previous point and convert it to a `csv` file by hand.

In [6]:
my_randoms_list = random.sample(range(1, 101), 25)

with open('ScientificComputingWithPython2023/data/data_int.txt', 'w') as fp:
    fp.write((str(my_randoms_list)))
# I have windows so I use type instead of cat
!type ScientificComputingWithPython2023\data\data_int.txt

matrix_5x5 = np.reshape(my_randoms_list, (5, 5))

with open('ScientificComputingWithPython2023/data/data_float.txt', 'w') as fm:
    fm.write((str(matrix_5x5)))

!type ScientificComputingWithPython2023\data\data_float.txt

replaced_content = ""
with open('ScientificComputingWithPython2023/data/data_float.txt', 'r', ) as fr:
    for line in fr:
     #   line = line.strip()
        new_line = line.replace(" ", ",")
        new_line = new_line.replace("[", "")
        new_line = new_line.replace("]", "")
        replaced_content = replaced_content + new_line
        
write_file = open("ScientificComputingWithPython2023/data/data_float.txt", "w")
write_file.write(replaced_content)

!type ScientificComputingWithPython2023\data\data_float.txt

[70, 64, 20, 8, 72, 1, 26, 46, 86, 49, 91, 65, 94, 11, 6, 16, 60, 82, 55, 2, 83, 56, 95, 3, 41]
[[70 64 20  8 72]
 [ 1 26 46 86 49]
 [91 65 94 11  6]
 [16 60 82 55  2]
 [83 56 95  3 41]]
,4,22,61,29,53
,27,92,42,80,21
,47,44,43,30,98
,64,60,93,38,94
,28,,6,36,76,58


2. **JSON files**

Load the file `user_data.json`, which can be found at:

- https://www.dropbox.com/s/sz5klcdpckc39hd/user_data.json

and filter the data by the "CreditCardType" when it equals to "American Express". Than save the data to a new CSV file.

In [11]:
dj = open('ScientificComputingWithPython2023/data/user_data.json')
user_data = json.load(dj)
dj.close()

filtered_data = [i for i in user_data if i["CreditCardType"] == "American Express"]

with open('ScientificComputingWithPython2023/data/user_data_filtered.csv', 'w') as file:
    for i in filtered_data:
        file.write(str(i) + '\n')
        print(i)


{'ID': '2', 'JobTitle': 'Investment  Advisor', 'EmailAddress': 'Clint_Thorpe5003@bulaffy.com', 'FirstNameLastName': 'Clint Thorpe', 'CreditCard': '7083-8766-0251-2345', 'CreditCardType': 'American Express'}
{'ID': '12', 'JobTitle': 'Retail Trainee', 'EmailAddress': 'Phillip_Carpenter9505@famism.biz', 'FirstNameLastName': 'Phillip Carpenter', 'CreditCard': '3657-0088-0820-5247', 'CreditCardType': 'American Express'}
{'ID': '28', 'JobTitle': 'Project Manager', 'EmailAddress': 'Russel_Graves1378@extex.org', 'FirstNameLastName': 'Russel Graves', 'CreditCard': '6718-4818-8011-6024', 'CreditCardType': 'American Express'}
{'ID': '39', 'JobTitle': 'Stockbroker', 'EmailAddress': 'Leanne_Newton1268@typill.biz', 'FirstNameLastName': 'Leanne Newton', 'CreditCard': '5438-0816-4166-4847', 'CreditCardType': 'American Express'}
{'ID': '57', 'JobTitle': 'Budget Analyst', 'EmailAddress': 'Tony_Giles1960@iatim.tech', 'FirstNameLastName': 'Tony Giles', 'CreditCard': '8130-3425-7573-7745', 'CreditCardType'

3. **CSV files with Pandas**

Load the file from this url:

- https://www.dropbox.com/s/kgshemfgk22iy79/mushrooms_categorized.csv

with Pandas. 

+ explore and print the DataFrame
+ calculate, using `groupby()`, the average value of each feature, separately for each class
+ save the file in a JSON format.

In [11]:
file_1 = open('ScientificComputingWithPython2023/data/mushrooms_categorized.csv')
df = pd.read_csv(file_1)
file_1.close()

print('mushrooms_categorized.csv: \n', df)

values_mean = df.groupby('class').mean()

file_2 = open('ScientificComputingWithPython2023/data/mushrooms_categorized_mod.json', 'w')
values_mean.to_json(file_2)
file_2.close()

mushrooms_categorized.csv: 
       class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0          

4. **Reading a database**

Get the database `sakila.db` from the lecture `06_dataio.ipynb`, and import the table `actors` as a Pandas dataframe. Using the dataframe, count how many actors have a first name that begins with `A`.

Hint: use the Series `.str` method to apply the Python string methods to the elements of a Series, see documentation.

In [7]:
conn = sql.connect('ScientificComputingWithPython2023/data/sakila.db')
cur = conn.cursor()

query = "SELECT * FROM actor"
results = cur.execute(query).fetchall()

df = pd.DataFrame(results)

cur.close()
conn.close()

df

column_name = df[1]
count = [x for x in column_name if x.startswith('A')]
print('The names starting with A are: \n', count)
print('Sum is', len(count))

The names starting with A are: 
 ['ALEC', 'AUDREY', 'ANNE', 'ANGELA', 'ADAM', 'ANGELINA', 'ALBERT', 'ADAM', 'ANGELA', 'ALBERT', 'AL', 'ALAN', 'AUDREY']
Sum is 13


5. **Reading the credit card numbers**

Get the binary file named `credit_card.dat` from this address:

- https://www.dropbox.com/s/8m0syw2tkul3dap/credit_card.dat

and convert the data into the real credit card number, knowing that:
- each line corresponds to a credit card number, which consists of 16 characters (which are numbers in the 0-9 range) divided in 4 blocks, with a whitespace between each block
- each character is written using a 6 bit binary representation (including the whitespace)
- the final 4 bits of each line are a padding used to determine the end of the line, and can be ignored

*Hint*: convert the binary numbers to the decimal representation first, and then use the `chr()` function to convert the latter to a char

In [52]:
res = ""
with open("ScientificComputingWithPython2023/data/credit_card.dat","rb") as file_dat:
    for line in file_dat:
        for j in range(0, len(line), 6):
            bin = line[j:j+6]
            dec = int(bin,2)
            res = res + chr(dec)
        res = res + "\n"
print(res)  


7648 5673 3775 2271

3257 8247 3354 2266

2722 0001 4011 6652

0661 3063 3742 3150

0432 1608 1462 4742

5827 2027 8785 7303

5774 8528 2087 1117

8140 1210 6352 2845

5764 1133 7301 7100

6456 1737 4126 6726

1228 8631 7382 0000

7051 0160 5374 3166

0618 3587 1630 6376

1545 5454 7444 5636

6735 3116 3202 6834

7287 5011 1547 8413

7033 2607 3328 4200

2568 5244 1874 5024

1684 2253 7570 7118

0672 2576 0575 6631

6332 8353 8787 1340

1813 3361 1175 4211

2477 6450 8840 2368

5512 3505 2563 1326

3083 7882 0621 0025

4521 5148 8045 0334

7563 3654 8713 5787

8324 2664 0476 5561

0565 2504 7168 3510

5107 5507 1767 0738

2462 1821 2448 1443

2788 0638 6861 6554

5851 5873 5474 0547

0670 1004 4013 2655

5874 5506 3048 0806

2805 5401 8462 1260

5083 8406 6310 1862

1076 1445 3013 2266

8440 4804 4844 5277

4758 6141 0686 1387

7586 0675 0315 2568

2544 1258 7432 5165

3474 5023 4434 5626

1410 0270 0434 5086

7315 4446 1104 4215

0224 7742 8300 0266

0170 2700 3145 0640

2006 2437 805

6. **Write data to a binary file**

a) Start from the `data/data_000637.txt` file that we have used during the previous lectures, and convert it to a binary file according to the format defined below:

*Hints*:
- Read the first 10 lines using Pandas
- Iterate over the DataFrame rows
- For every row, ``pack'' the values (features) into a single 64-bit word, according to the format specified above. Use bit-wise shifts and operators to do so.
- Write each 64-bit word to a binary file. You can use `struct` in this way:
```
binary_file.write( struct.pack('<q', word) )
```
where `word` is the 64-bit word.
- Close the file after completing the loop.

b) Check that the binary file is correctly written by reading it with the code used in the lecture `06_OSEMN.ipynb`, and verify that the content of the `txt` and binary files is consistent.

c) What is the difference of the size on disk between equivalent `txt` and binary files?

In [10]:
d = pd.DataFrame(pd.read_csv('ScientificComputingWithPython2023/data/data_000637.txt',nrows=10))

with open('ScientificComputingWithPython2023/data/binary_file.dat','wb') as file_bin:
    for line in d.values:    
        file_bin.write(struct.pack('<q', (line[5]<<0)+(line[4]<<5)+(line[3]<<17)+(line[2]<<49)+(line[1]<<58)+(line[0]<<62)))

# check with the code used in lecture:

data = {}

with open('ScientificComputingWithPython2023/data/binary_file.dat', 'rb') as file:
    file_content = file.read()
    word_counter = 0
    word_size = 8 # size of the word in bytes
    for i in range(0, len(file_content), word_size):
        word_counter += 1
        word = struct.unpack('<q', file_content[i : i + word_size])[0] # get an 8-byte word
        head     = (word >> 62) & 0x3
        fpga     = (word >> 58) & 0xF
        tdc_chan = (word >> 49) & 0x1FF
        orb_cnt  = (word >> 17) & 0xFFFFFFFF
        bx       = (word >> 5 ) & 0xFFF
        tdc_meas = (word >> 0 ) & 0x1F
        #if i == 0: print ('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format('HEAD', 'FPGA', 'CHANNEL', 'ORBIT_CNT', 'BX_CNT', 'TDC_MEAS'))
        #print('{0}\t{1}\t{2}\t{3}\t{4}\t{5}'.format(head, fpga, tdc_chan, orb_cnt, bx, tdc_meas))
        entry = {'HEAD' : head, 'FPGA' : fpga, 'CHANNEL' : tdc_chan, 'ORBIT_CNT' : orb_cnt, 'BX_CNT' : bx, 'TDC_MEAS' : tdc_meas}
        #df = df.append(entry, ignore_index=True)
        data[word_counter] = entry
        
df = pd.DataFrame(data).T

print('The size of txt file is 32402 KB and the size of bin file is 10240 KB')

print('First 10 rows of the data frame to check:')
df

The size of txt file is 32402 KB and the size of bin file is 10240 KB
First 10 rows of the data frame to check:


HEAD  FPGA  CHANNEL   ORBIT_CNT  BX_CNT  TDC_MEAS
1      1     0      123  3869200167    2374        26
2      1     0      124  3869200167    2374        27
3      1     0       63  3869200167    2553        28
4      1     0       64  3869200167    2558        19
5      1     0       64  3869200167    2760        25
6      1     0       63  3869200167    2762         4
7      1     0       61  3869200167    2772        14
8      1     0      139  3869200167    2776         0
9      1     0       62  3869200167    2774        21
10     1     0       60  3869200167    2788         7