1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [1]:
import numpy as np
avg_list_column = []
avg_list_row = []
m = np.arange(12).reshape((3,4))
print(m)
print(f'the mean for columns is : {np.median(m,axis=0)}')
print(f'the mean for rows is : {np.median(m,axis=1)}')
print(f'the total media is : {np.median(m)}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
the mean for columns is : [4. 5. 6. 7.]
the mean for rows is : [1.5 5.5 9.5]
the total media is : 5.5


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [2]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
first_solution = np.outer(u,v)
print(f'the first solution is :\n{first_solution}')
second_list = np.array([i*j for i in u for j in v]).reshape(4,4)
print(f'the second solution is :\n{second_list}')
third = np.tile(u, 2)
print(third)

the first solution is :
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
the second solution is :
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
[1 3 5 7 1 3 5 7]


3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

In [3]:
first_array = np.random.uniform(low=0 , high=3 , size=60)
final_array = first_array.reshape(10,6)
print(final_array)

[[2.27002974 2.91404727 2.71063964 2.63568287 1.83759704 0.4634219 ]
 [1.89567579 2.70936719 0.15780676 2.80132161 2.50530683 0.83514897]
 [0.21253949 0.66624958 0.53594051 0.02137766 2.15894921 2.98567912]
 [1.98478161 1.83150797 1.35231598 0.35185568 2.70420178 2.75403943]
 [1.76278874 0.75184608 0.33333467 0.87298003 0.45328482 1.34014377]
 [0.65464162 1.85551265 0.62121967 2.16071488 1.96623759 2.25680049]
 [2.19703499 0.90120882 0.27999562 1.6844617  2.58109821 1.87122989]
 [0.79387578 2.90301049 1.68425425 0.41820357 1.03353833 2.29807901]
 [0.25454918 2.66148357 0.66335478 1.13562845 0.62129399 1.76382483]
 [2.85491673 0.79581685 2.83143193 1.98632329 1.77624803 2.22427473]]


4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [4]:
import math
difference_list = []
primary_array = np.linspace(2,2*math.pi,100)
print(f'the every 10th element is : \n {primary_array[::10]}')
print('\n')
print(f'the reverse array is : \n {primary_array[::-1]}')
for i in primary_array :
    if abs(math.sin(i) - math.cos(i)) < 0.1 :
        difference_list.append(i)
print('\n')        
print(f'this is the list of elements that the absolute difference between sin and cos is < 0.1 : \n {difference_list}')

the every 10th element is : 
 [2.         2.43264498 2.86528996 3.29793494 3.73057992 4.1632249
 4.59586988 5.02851486 5.46115984 5.89380482]


the reverse array is : 
 [6.28318531 6.23992081 6.19665631 6.15339181 6.11012731 6.06686282
 6.02359832 5.98033382 5.93706932 5.89380482 5.85054033 5.80727583
 5.76401133 5.72074683 5.67748233 5.63421784 5.59095334 5.54768884
 5.50442434 5.46115984 5.41789535 5.37463085 5.33136635 5.28810185
 5.24483735 5.20157286 5.15830836 5.11504386 5.07177936 5.02851486
 4.98525037 4.94198587 4.89872137 4.85545687 4.81219237 4.76892788
 4.72566338 4.68239888 4.63913438 4.59586988 4.55260539 4.50934089
 4.46607639 4.42281189 4.37954739 4.33628289 4.2930184  4.2497539
 4.2064894  4.1632249  4.1199604  4.07669591 4.03343141 3.99016691
 3.94690241 3.90363791 3.86037342 3.81710892 3.77384442 3.73057992
 3.68731542 3.64405093 3.60078643 3.55752193 3.51425743 3.47099293
 3.42772844 3.38446394 3.34119944 3.29793494 3.25467044 3.21140595
 3.16814145 3.12487695 3.081

5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [5]:
row_array = np.arange(1,11)
column_array = row_array[:,None]
result = row_array * column_array
print(f'the trace of the matrix is : \n {np.trace(result)}')
print('\n')
flip_result = np.fliplr(result)
anti_diagonal_array = flip_result.diagonal()
print(f'the anti-diagonal matrix is : \n {anti_diagonal_array}')
print(f'\n')
print(f'the diagonal offset by 1 upwards is : \n {np.diagonal(result,offset=1)}')

the trace of the matrix is : 
 385


the anti-diagonal matrix is : 
 [10 18 24 28 30 30 28 24 18 10]


the diagonal offset by 1 upwards is : 
 [ 2  6 12 20 30 42 56 72 90]


6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [6]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544,1913, 2448])
distance_array = np.abs(mileposts - mileposts[:, np.newaxis])
distance_array
print("\ndistance: \n",distance_array)
print("\n Converted from miles in: \n", distance_array/0.62137119)



distance: 
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]

 Converted from miles in: 
 [[   0.          318.65011315  487.63123376 1184.47718826 1401.73862905
  1890.97920681 2373.78240855 2484.82714495 3078.67508309 3939.67412619]
 [ 318.65011315    0.          168.98112061  865.82707512 1083.0885159
  1572.32909366 2055.1322954  2166.1770318  2760.02496994 3621.02401304]
 [ 487.63123376  168.98112061    0.          696.84595451  914.10739529
  1403.34797305 1886.15117479 1997.19591119 2591.04384933 3452.042

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [7]:
N = 20
prime_list = []
def prime_checker(selected_number):
    counter = 0
    for i in range (1,selected_number+1):
        if selected_number % i  == 0 :
            counter += 1
    if counter <= 2 :
        counter = 0
        return selected_number

def prime_identifier(N):
    for i in range (2,N+1):
        if prime_checker(i) != None :
            prime_list.append(i)
    return prime_list        
print(prime_identifier(N))

[2, 3, 5, 7, 11, 13, 17, 19]


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [8]:
random_array = np.random.randint(-1,2,(1000,200))
random_array[random_array==0] = 1
print(f'the walkers * steps  = \n {random_array}')
sum_of_row = np.sum(random_array,axis=1)
print(f'the sum for each row is equal to : \n {sum_of_row}')
square = np.square(sum_of_row)
print(f'the square of the elements is : \n {square}')

the walkers * steps  = 
 [[ 1  1  1 ...  1 -1 -1]
 [ 1  1  1 ...  1  1  1]
 [-1  1  1 ...  1 -1  1]
 ...
 [-1  1  1 ... -1  1 -1]
 [-1  1  1 ...  1  1  1]
 [ 1 -1 -1 ...  1  1  1]]
the sum for each row is equal to : 
 [ 68  46  78  64  76  68  64  84  88  54  34  64  60  64  88  78  66  64
  68  76  62  54  32  78  66  70  60  78  48  54  52  76  74  68  42  54
  60  84  56  46  42  82  72  76  64  82  56  48  84  70  60  68  68  86
  48  60  58  72  56  56  60  48  66  40  68  78  98  42  52  62  82  60
  70  72  78  84  50  76  60  70  60  72  64  60  80  72  64  86  72  52
  72  54  80  54  72  48  64  74  46  80  56  48  50  70  86 100  64  80
  36  52  54  74  82  84  56  90  74  74  62  78  40  86  64  60  60  82
  76  46  48  78  68  80  76  44  56  50  70  70  74  62  78  68  82  56
  68  76  90  52  64  60  60 100  60  56  62  86  66  68  52  78  60  94
  62  40  58  84  90  64  94  50  54  80  62  80  76  64  72  74  98  48
  58  96  60  74  62  92 100  80  78  54  74  88  66